#include "test_decode_flags_adapter.h"
#include "cdisasm/cdisasm.h"
#if USE_DISASM_FORMAT
#include "cdisasm/cdisasm_format.h"
#endif
#include <stdio.h>
#include <string.h>

static uint32_t dw(uint32_t w,cdisasm_arm_cpu_id c,cdisasm_arm_instruction*i){uint8_t b[4]={(uint8_t)w,(uint8_t)(w>>8),(uint8_t)(w>>16),(uint8_t)(w>>24)};return cdisasm_arm_decode(c,3,b,4,0,0,i);}
int main(void){cdisasm_arm_instruction i;
#if USE_EXTRA_OPCODES
{static const uint32_t pw[2]={UINT32_C(0xc19f7fff),UINT32_C(0xc19fffaf)};static const unsigned pf[2]={3993,4041},pc[2]={2,4};unsigned pk;for(pk=0;pk<2;pk++){if(dw(pw[pk],CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=CDISASM_ARM_NAME_FMLAL||i.form_id!=pf[pk]||i.instruction_flags!=UINT32_C(0x05402000)||i.operand_count!=3||i.operand[0].extend_type!=2||i.operand[0].register_list!=pc[pk]||i.operand[1].extend_type!=1||i.operand[1].register_list!=(UINT16_C(0x0100)|pc[pk])||i.operand[2].extend_type!=1||i.operand[2].imm!=15)return 1;}if(dw(pw[0],CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{static const uint32_t zw[5]={UINT32_C(0xc18ffbfb),UINT32_C(0xc1929000),UINT32_C(0xc194bd0d),UINT32_C(0xc196d616),UINT32_C(0xc19fff9b)};static const cdisasm_arm_name_id znm[5]={CDISASM_ARM_NAME_BFMLSL,CDISASM_ARM_NAME_FMLAL,CDISASM_ARM_NAME_FMLSL,CDISASM_ARM_NAME_BFMLAL,CDISASM_ARM_NAME_BFMLSL};static const unsigned zf[5]={3952,4038,4040,4037,4039},zc[5]={2,4,4,4,4};unsigned zk;for(zk=0;zk<5;zk++){if(dw(zw[zk],CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=znm[zk]||i.form_id!=zf[zk]||i.instruction_flags!=UINT32_C(0x05402000)||i.operand_count!=3||i.operand[0].register_list!=zc[zk]||i.operand[1].extend_type!=2||i.operand[2].extend_type!=2)return 1;}if(dw(zw[1],CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{static const uint32_t yw[4]={UINT32_C(0xc1921000),UINT32_C(0xc1943d0d),UINT32_C(0xc1965616),UINT32_C(0xc19f7fdb)};static const cdisasm_arm_name_id yn[4]={CDISASM_ARM_NAME_FMLAL,CDISASM_ARM_NAME_FMLSL,CDISASM_ARM_NAME_BFMLAL,CDISASM_ARM_NAME_BFMLSL};static const unsigned yf[4]={3990,3992,3989,3991};unsigned yk;for(yk=0;yk<4;yk++){if(dw(yw[yk],CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=yn[yk]||i.form_id!=yf[yk]||i.instruction_flags!=UINT32_C(0x05402000)||i.operand_count!=3||i.operand[0].type!=CDISASM_ARM_OPERAND_TILE||i.operand[0].register_list!=2||i.operand[0].extend_type!=4||i.operand[1].type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||i.operand[1].register_list!=UINT16_C(0x0102)||i.operand[2].flags!=CDISASM_ARM_OPERAND_FLAG_HAS_LANE)return 1;}if(dw(yw[0],CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{static const uint32_t xw[2]={UINT32_C(0xc1c20020),UINT32_C(0xc1cfefeb)};static const unsigned xl[2]={0,15};unsigned xk;for(xk=0;xk<2;xk++){if(dw(xw[xk],CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=CDISASM_ARM_NAME_FMLAL||i.form_id!=3954||i.instruction_flags!=UINT32_C(0x05402000)||i.operand_count!=3||i.operand[0].type!=CDISASM_ARM_OPERAND_TILE||i.operand[0].extend_type!=2||i.operand[1].extend_type!=1||i.operand[2].extend_type!=1||i.operand[2].imm!=xl[xk])return 1;}if(dw(xw[0],CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{static const uint32_t fw[3]={UINT32_C(0xc1821020),UINT32_C(0xc184bc69),UINT32_C(0xc1865cb2)};static const cdisasm_arm_name_id fn[3]={CDISASM_ARM_NAME_FMLAL,CDISASM_ARM_NAME_FMLSL,CDISASM_ARM_NAME_BFMLAL};static const unsigned ff[3]={3951,3953,3950},lanes[3]={0,7,3};unsigned k;for(k=0;k<3;k++){if(dw(fw[k],CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=fn[k]||i.form_id!=ff[k]||i.instruction_flags!=UINT32_C(0x05402000)||i.operand_count!=3||i.operand[0].type!=CDISASM_ARM_OPERAND_TILE||i.operand[0].register_list!=2||i.operand[0].extend_type!=4||i.operand[1].extend_type!=2||i.operand[2].extend_type!=2||i.operand[2].imm!=lanes[k])return 1;}if(dw(fw[0],CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
static const cdisasm_arm_name_id n[4]={CDISASM_ARM_NAME_SMLAL,CDISASM_ARM_NAME_SMLSL,CDISASM_ARM_NAME_UMLAL,CDISASM_ARM_NAME_UMLSL};unsigned op,rv,off,zn,zm,lane;
for(op=0;op<4;op++)for(rv=0;rv<4;rv++)for(off=0;off<8;off++)for(zn=0;zn<32;zn++)for(zm=0;zm<16;zm++)for(lane=0;lane<8;lane++){
uint32_t w=UINT32_C(0xc1c01000)|(op<<3)|(rv<<13)|off|(zn<<5)|(zm<<16)|((lane&4)<<13)|((lane&3)<<10);const cdisasm_arm_operand*t,*a,*b;
if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=n[op]||i.form_id!=3955+op||i.instruction_flags!=UINT32_C(0x05400000)||i.operand_count!=3)return 1;t=&i.operand[0];a=&i.operand[1];b=&i.operand[2];
if(t->type!=CDISASM_ARM_OPERAND_TILE||t->reg!=CDISASM_ARM_REG_ZA||t->base_reg!=CDISASM_ARM_REG_W8+rv||t->imm!=off*2||t->register_list!=2||t->extend_type!=4||t->access!=CDISASM_OPERAND_ACCESS_READ_WRITE)return 1;
if(a->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER||a->reg!=CDISASM_ARM_REG_Z0+zn||a->extend_type!=2||a->access!=CDISASM_OPERAND_ACCESS_READ)return 1;
if(b->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER||b->reg!=CDISASM_ARM_REG_Z0+zm||b->extend_type!=2||b->flags!=CDISASM_ARM_OPERAND_FLAG_HAS_LANE||b->imm!=lane||b->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc1c01000),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;
{static const cdisasm_arm_name_id fn[4]={CDISASM_ARM_NAME_FMLA,CDISASM_ARM_NAME_FMLS,CDISASM_ARM_NAME_BFMLA,CDISASM_ARM_NAME_BFMLS};static const unsigned ff[4]={3965,3967,3966,3968};unsigned q,r,o,z,m,l;for(q=0;q<4;q++)for(r=0;r<4;r++)for(o=0;o<8;o++)for(z=0;z<16;z++)for(m=0;m<16;m++)for(l=0;l<8;l++){
uint32_t w=UINT32_C(0xc1101000)|(q<<4)|(r<<13)|o|(z<<6)|(m<<16)|((l&6)<<9)|((l&1)<<3);const cdisasm_arm_operand*t,*v,*s;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=fn[q]||i.form_id!=ff[q]||i.instruction_flags!=UINT32_C(0x05402000)||i.operand_count!=3)return 1;t=&i.operand[0];v=&i.operand[1];s=&i.operand[2];
if(t->type!=CDISASM_ARM_OPERAND_TILE||t->reg!=CDISASM_ARM_REG_ZA||t->base_reg!=CDISASM_ARM_REG_W8+r||t->imm!=o||t->register_list!=2||t->extend_type!=2||t->access!=CDISASM_OPERAND_ACCESS_READ_WRITE)return 1;
if(v->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||v->reg!=CDISASM_ARM_REG_Z0+z*2||v->register_list!=UINT16_C(0x0102)||v->extend_type!=2||v->access!=CDISASM_OPERAND_ACCESS_READ)return 1;
if(s->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER||s->reg!=CDISASM_ARM_REG_Z0+m||s->extend_type!=2||s->flags!=CDISASM_ARM_OPERAND_FLAG_HAS_LANE||s->imm!=l||s->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc1101000),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{static const cdisasm_arm_name_id fn[4]={CDISASM_ARM_NAME_FMLA,CDISASM_ARM_NAME_FMLS,CDISASM_ARM_NAME_BFMLA,CDISASM_ARM_NAME_BFMLS};static const unsigned ff[4]={4013,4015,4014,4016};unsigned q,r,o,z,m,l;for(q=0;q<4;q++)for(r=0;r<4;r++)for(o=0;o<8;o++)for(z=0;z<8;z++)for(m=0;m<16;m++)for(l=0;l<8;l++){
uint32_t w=UINT32_C(0xc1109000)|(q<<4)|(r<<13)|o|(z<<7)|(m<<16)|((l&6)<<9)|((l&1)<<3);const cdisasm_arm_operand*t,*v,*s;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=fn[q]||i.form_id!=ff[q]||i.instruction_flags!=UINT32_C(0x05402000)||i.operand_count!=3)return 1;t=&i.operand[0];v=&i.operand[1];s=&i.operand[2];
if(t->type!=CDISASM_ARM_OPERAND_TILE||t->reg!=CDISASM_ARM_REG_ZA||t->base_reg!=CDISASM_ARM_REG_W8+r||t->imm!=o||t->register_list!=4||t->extend_type!=2||t->access!=CDISASM_OPERAND_ACCESS_READ_WRITE)return 1;
if(v->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||v->reg!=CDISASM_ARM_REG_Z0+z*4||v->register_list!=UINT16_C(0x0104)||v->extend_type!=2||v->access!=CDISASM_OPERAND_ACCESS_READ)return 1;
if(s->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER||s->reg!=CDISASM_ARM_REG_Z0+m||s->extend_type!=2||s->flags!=CDISASM_ARM_OPERAND_FLAG_HAS_LANE||s->imm!=l||s->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc1109000),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{unsigned q,r,o,z,m,l;for(q=0;q<4;q++)for(r=0;r<4;r++)for(o=0;o<4;o++)for(z=0;z<8;z++)for(m=0;m<16;m++)for(l=0;l<8;l++){
uint32_t w=UINT32_C(0xc1d09000)|(q<<3)|(r<<13)|o|(z<<7)|(m<<16)|((l&6)<<9)|((l&1)<<2);const cdisasm_arm_operand*t,*v,*s;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=n[q]||i.form_id!=4048+q||i.instruction_flags!=UINT32_C(0x05400000)||i.operand_count!=3)return 1;t=&i.operand[0];v=&i.operand[1];s=&i.operand[2];
if(t->type!=CDISASM_ARM_OPERAND_TILE||t->reg!=CDISASM_ARM_REG_ZA||t->base_reg!=CDISASM_ARM_REG_W8+r||t->imm!=o*2||t->register_list!=4||t->extend_type!=4||t->access!=CDISASM_OPERAND_ACCESS_READ_WRITE)return 1;
if(v->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||v->reg!=CDISASM_ARM_REG_Z0+z*4||v->register_list!=UINT16_C(0x0104)||v->extend_type!=2||v->access!=CDISASM_OPERAND_ACCESS_READ)return 1;
if(s->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER||s->reg!=CDISASM_ARM_REG_Z0+m||s->extend_type!=2||s->flags!=CDISASM_ARM_OPERAND_FLAG_HAS_LANE||s->imm!=l||s->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc1d09000),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{unsigned q,r,o,z,m,l;for(q=0;q<4;q++)for(r=0;r<4;r++)for(o=0;o<4;o++)for(z=0;z<16;z++)for(m=0;m<16;m++)for(l=0;l<8;l++){
uint32_t w=UINT32_C(0xc1d01000)|(q<<3)|(r<<13)|o|(z<<6)|(m<<16)|((l&6)<<9)|((l&1)<<2);const cdisasm_arm_operand*t,*v,*s;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=n[q]||i.form_id!=4000+q||i.instruction_flags!=UINT32_C(0x05400000)||i.operand_count!=3)return 1;t=&i.operand[0];v=&i.operand[1];s=&i.operand[2];
if(t->type!=CDISASM_ARM_OPERAND_TILE||t->reg!=CDISASM_ARM_REG_ZA||t->base_reg!=CDISASM_ARM_REG_W8+r||t->imm!=o*2||t->register_list!=2||t->extend_type!=4||t->access!=CDISASM_OPERAND_ACCESS_READ_WRITE)return 1;
if(v->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||v->reg!=CDISASM_ARM_REG_Z0+z*2||v->register_list!=UINT16_C(0x0102)||v->extend_type!=2||v->access!=CDISASM_OPERAND_ACCESS_READ)return 1;
if(s->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER||s->reg!=CDISASM_ARM_REG_Z0+m||s->extend_type!=2||s->flags!=CDISASM_ARM_OPERAND_FLAG_HAS_LANE||s->imm!=l||s->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc1d01000),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{static const cdisasm_arm_name_id dn[4]={CDISASM_ARM_NAME_FMLA,CDISASM_ARM_NAME_SDOT,CDISASM_ARM_NAME_FMLS,CDISASM_ARM_NAME_UDOT};unsigned q,r,o,z,m,l;for(q=0;q<4;q++)for(r=0;r<4;r++)for(o=0;o<8;o++)for(z=0;z<16;z++)for(m=0;m<16;m++)for(l=0;l<2;l++){
uint32_t w=UINT32_C(0xc1d00000)|(q<<3)|(r<<13)|o|(z<<6)|(m<<16)|(l<<10);unsigned sz=(q&1)?2:8;const cdisasm_arm_operand*t,*v,*s;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=dn[q]||i.form_id!=3996+q||i.instruction_flags!=(UINT32_C(0x05400000)|((q&1)?0:CDISASM_ARM_INSTRUCTION_FLAG_FLOATING_POINT))||i.operand_count!=3)return 1;t=&i.operand[0];v=&i.operand[1];s=&i.operand[2];
if(t->type!=CDISASM_ARM_OPERAND_TILE||t->reg!=CDISASM_ARM_REG_ZA||t->base_reg!=CDISASM_ARM_REG_W8+r||t->imm!=o||t->register_list!=2||t->extend_type!=8||t->access!=CDISASM_OPERAND_ACCESS_READ_WRITE)return 1;
if(v->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||v->reg!=CDISASM_ARM_REG_Z0+z*2||v->register_list!=UINT16_C(0x0102)||v->extend_type!=sz||v->access!=CDISASM_OPERAND_ACCESS_READ)return 1;
if(s->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER||s->reg!=CDISASM_ARM_REG_Z0+m||s->extend_type!=sz||s->flags!=CDISASM_ARM_OPERAND_FLAG_HAS_LANE||s->imm!=l||s->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc1d00000),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{static const cdisasm_arm_name_id dn[4]={CDISASM_ARM_NAME_FMLA,CDISASM_ARM_NAME_SDOT,CDISASM_ARM_NAME_FMLS,CDISASM_ARM_NAME_UDOT};static const unsigned df[4]={4042,4043,4045,4046};unsigned q,r,o,z,m,l;for(q=0;q<4;q++)for(r=0;r<4;r++)for(o=0;o<8;o++)for(z=0;z<8;z++)for(m=0;m<16;m++)for(l=0;l<2;l++){
uint32_t w=UINT32_C(0xc1d08000)|(q<<3)|(r<<13)|o|(z<<7)|(m<<16)|(l<<10);unsigned sz=(q&1)?2:8;const cdisasm_arm_operand*t,*v,*s;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=dn[q]||i.form_id!=df[q]||i.instruction_flags!=(UINT32_C(0x05400000)|((q&1)?0:CDISASM_ARM_INSTRUCTION_FLAG_FLOATING_POINT))||i.operand_count!=3)return 1;t=&i.operand[0];v=&i.operand[1];s=&i.operand[2];
if(t->type!=CDISASM_ARM_OPERAND_TILE||t->reg!=CDISASM_ARM_REG_ZA||t->base_reg!=CDISASM_ARM_REG_W8+r||t->imm!=o||t->register_list!=4||t->extend_type!=8||t->access!=CDISASM_OPERAND_ACCESS_READ_WRITE)return 1;
if(v->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||v->reg!=CDISASM_ARM_REG_Z0+z*4||v->register_list!=UINT16_C(0x0104)||v->extend_type!=sz||v->access!=CDISASM_OPERAND_ACCESS_READ)return 1;
if(s->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER||s->reg!=CDISASM_ARM_REG_Z0+m||s->extend_type!=sz||s->flags!=CDISASM_ARM_OPERAND_FLAG_HAS_LANE||s->imm!=l||s->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc1d08000),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{static const cdisasm_arm_name_id vn[2]={CDISASM_ARM_NAME_SVDOT,CDISASM_ARM_NAME_UVDOT};static const unsigned vf[2]={4044,4047};unsigned q,r,o,z,m,l;for(q=0;q<2;q++)for(r=0;r<4;r++)for(o=0;o<8;o++)for(z=0;z<8;z++)for(m=0;m<16;m++)for(l=0;l<2;l++){
uint32_t w=UINT32_C(0xc1d08808)|(q<<4)|(r<<13)|o|(z<<7)|(m<<16)|(l<<10);const cdisasm_arm_operand*t,*v,*s;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=vn[q]||i.form_id!=vf[q]||i.instruction_flags!=UINT32_C(0x05400000)||i.operand_count!=3)return 1;t=&i.operand[0];v=&i.operand[1];s=&i.operand[2];
if(t->type!=CDISASM_ARM_OPERAND_TILE||t->reg!=CDISASM_ARM_REG_ZA||t->base_reg!=CDISASM_ARM_REG_W8+r||t->imm!=o||t->register_list!=4||t->extend_type!=8||t->access!=CDISASM_OPERAND_ACCESS_READ_WRITE)return 1;
if(v->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||v->reg!=CDISASM_ARM_REG_Z0+z*4||v->register_list!=UINT16_C(0x0104)||v->extend_type!=2||v->access!=CDISASM_OPERAND_ACCESS_READ)return 1;
if(s->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER||s->reg!=CDISASM_ARM_REG_Z0+m||s->extend_type!=2||s->flags!=CDISASM_ARM_OPERAND_FLAG_HAS_LANE||s->imm!=l||s->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc1d08808),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{static const cdisasm_arm_name_id vn[2]={CDISASM_ARM_NAME_SVDOT,CDISASM_ARM_NAME_UVDOT};static const unsigned vf2[2]={3972,3980},vf4[2]={4020,4028};unsigned c,q,r,o,z,m,l;for(c=2;c<=4;c+=2)for(q=0;q<2;q++)for(r=0;r<4;r++)for(o=0;o<8;o++)for(z=0;z<(c==4?8:16);z++)for(m=0;m<16;m++)for(l=0;l<4;l++){
uint32_t w=(c==4?UINT32_C(0xc1508020):UINT32_C(0xc1500020))|(q<<4)|(r<<13)|o|(z<<(c==4?7:6))|(m<<16)|(l<<10);unsigned sz=c==4?1:2;const cdisasm_arm_operand*t,*v,*s;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=vn[q]||i.form_id!=(c==4?vf4[q]:vf2[q])||i.instruction_flags!=UINT32_C(0x05400000)||i.operand_count!=3)return 1;t=&i.operand[0];v=&i.operand[1];s=&i.operand[2];
if(t->type!=CDISASM_ARM_OPERAND_TILE||t->reg!=CDISASM_ARM_REG_ZA||t->base_reg!=CDISASM_ARM_REG_W8+r||t->imm!=o||t->register_list!=c||t->extend_type!=4||t->access!=CDISASM_OPERAND_ACCESS_READ_WRITE)return 1;
if(v->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||v->reg!=CDISASM_ARM_REG_Z0+z*c||v->register_list!=(uint16_t)(0x0100|c)||v->extend_type!=sz||v->access!=CDISASM_OPERAND_ACCESS_READ)return 1;
if(s->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER||s->reg!=CDISASM_ARM_REG_Z0+m||s->extend_type!=sz||s->flags!=CDISASM_ARM_OPERAND_FLAG_HAS_LANE||s->imm!=l||s->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc1500020),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{static const cdisasm_arm_name_id mn[2]={CDISASM_ARM_NAME_USDOT,CDISASM_ARM_NAME_SUDOT};static const unsigned mf2[2]={3978,3983},mf4[2]={4026,4032};unsigned c,q,r,o,z,m,l;for(c=2;c<=4;c+=2)for(q=0;q<2;q++)for(r=0;r<4;r++)for(o=0;o<8;o++)for(z=0;z<(c==4?8:16);z++)for(m=0;m<16;m++)for(l=0;l<4;l++){
uint32_t w=(c==4?UINT32_C(0xc1509028):UINT32_C(0xc1501028))|(q<<4)|(r<<13)|o|(z<<(c==4?7:6))|(m<<16)|(l<<10);const cdisasm_arm_operand*t,*v,*s;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=mn[q]||i.form_id!=(c==4?mf4[q]:mf2[q])||i.instruction_flags!=UINT32_C(0x05400000)||i.operand_count!=3)return 1;t=&i.operand[0];v=&i.operand[1];s=&i.operand[2];
if(t->type!=CDISASM_ARM_OPERAND_TILE||t->reg!=CDISASM_ARM_REG_ZA||t->base_reg!=CDISASM_ARM_REG_W8+r||t->imm!=o||t->register_list!=c||t->extend_type!=4||t->access!=CDISASM_OPERAND_ACCESS_READ_WRITE)return 1;
if(v->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||v->reg!=CDISASM_ARM_REG_Z0+z*c||v->register_list!=(uint16_t)(0x0100|c)||v->extend_type!=1||v->access!=CDISASM_OPERAND_ACCESS_READ)return 1;
if(s->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER||s->reg!=CDISASM_ARM_REG_Z0+m||s->extend_type!=1||s->flags!=CDISASM_ARM_OPERAND_FLAG_HAS_LANE||s->imm!=l||s->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc1501028),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{unsigned q,r,o,z,m;for(q=0;q<4;q++)for(r=0;r<4;r++)for(o=0;o<4;o++)for(z=0;z<8;z++)for(m=0;m<8;m++){
uint32_t w=UINT32_C(0xc1e10800)|(q<<3)|(r<<13)|o|(z<<7)|(m<<18);const cdisasm_arm_operand*t,*a,*b;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=n[q]||i.form_id!=4186+q||i.instruction_flags!=UINT32_C(0x05400000)||i.operand_count!=3)return 1;t=&i.operand[0];a=&i.operand[1];b=&i.operand[2];
if(t->type!=CDISASM_ARM_OPERAND_TILE||t->reg!=CDISASM_ARM_REG_ZA||t->base_reg!=CDISASM_ARM_REG_W8+r||t->imm!=o*2||t->register_list!=4||t->extend_type!=4||t->access!=CDISASM_OPERAND_ACCESS_READ_WRITE)return 1;
if(a->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||a->reg!=CDISASM_ARM_REG_Z0+z*4||a->register_list!=UINT16_C(0x0104)||a->extend_type!=2||a->access!=CDISASM_OPERAND_ACCESS_READ)return 1;
if(b->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||b->reg!=CDISASM_ARM_REG_Z0+m*4||b->register_list!=UINT16_C(0x0104)||b->extend_type!=2||b->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc1e10800),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{unsigned q,r,o,z,m;for(q=0;q<4;q++)for(r=0;r<4;r++)for(o=0;o<4;o++)for(z=0;z<16;z++)for(m=0;m<16;m++){
uint32_t w=UINT32_C(0xc1e00800)|(q<<3)|(r<<13)|o|(z<<6)|(m<<17);const cdisasm_arm_operand*t,*a,*b;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=n[q]||i.form_id!=4146+q||i.instruction_flags!=UINT32_C(0x05400000)||i.operand_count!=3)return 1;t=&i.operand[0];a=&i.operand[1];b=&i.operand[2];
if(t->type!=CDISASM_ARM_OPERAND_TILE||t->reg!=CDISASM_ARM_REG_ZA||t->base_reg!=CDISASM_ARM_REG_W8+r||t->imm!=o*2||t->register_list!=2||t->extend_type!=4||t->access!=CDISASM_OPERAND_ACCESS_READ_WRITE)return 1;
if(a->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||a->reg!=CDISASM_ARM_REG_Z0+z*2||a->register_list!=UINT16_C(0x0102)||a->extend_type!=2||a->access!=CDISASM_OPERAND_ACCESS_READ)return 1;
if(b->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||b->reg!=CDISASM_ARM_REG_Z0+m*2||b->register_list!=UINT16_C(0x0102)||b->extend_type!=2||b->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc1e00800),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{static const cdisasm_arm_name_id pn[4]={CDISASM_ARM_NAME_FMLA,CDISASM_ARM_NAME_BFMLA,CDISASM_ARM_NAME_FMLS,CDISASM_ARM_NAME_BFMLS};unsigned q,r,o,z,m;for(q=0;q<4;q++)for(r=0;r<4;r++)for(o=0;o<8;o++)for(z=0;z<16;z++)for(m=0;m<16;m++){
uint32_t w=UINT32_C(0xc1a01008)|((q&1)<<22)|((q>>1)<<4)|(r<<13)|o|(z<<6)|(m<<17);const cdisasm_arm_operand*t,*a,*b;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=pn[q]||i.form_id!=4154+q||i.instruction_flags!=UINT32_C(0x05402000)||i.operand_count!=3)return 1;t=&i.operand[0];a=&i.operand[1];b=&i.operand[2];
if(t->type!=CDISASM_ARM_OPERAND_TILE||t->reg!=CDISASM_ARM_REG_ZA||t->base_reg!=CDISASM_ARM_REG_W8+r||t->imm!=o||t->register_list!=2||t->extend_type!=2||t->access!=CDISASM_OPERAND_ACCESS_READ_WRITE)return 1;
if(a->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||a->reg!=CDISASM_ARM_REG_Z0+z*2||a->register_list!=UINT16_C(0x0102)||a->extend_type!=2||a->access!=CDISASM_OPERAND_ACCESS_READ)return 1;
if(b->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||b->reg!=CDISASM_ARM_REG_Z0+m*2||b->register_list!=UINT16_C(0x0102)||b->extend_type!=2||b->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc1a01008),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{static const cdisasm_arm_name_id pn[4]={CDISASM_ARM_NAME_FMLA,CDISASM_ARM_NAME_BFMLA,CDISASM_ARM_NAME_FMLS,CDISASM_ARM_NAME_BFMLS};unsigned q,r,o,z,m;for(q=0;q<4;q++)for(r=0;r<4;r++)for(o=0;o<8;o++)for(z=0;z<8;z++)for(m=0;m<8;m++){
uint32_t w=UINT32_C(0xc1a11008)|((q&1)<<22)|((q>>1)<<4)|(r<<13)|o|(z<<7)|(m<<18);const cdisasm_arm_operand*t,*a,*b;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=pn[q]||i.form_id!=4194+q||i.instruction_flags!=UINT32_C(0x05402000)||i.operand_count!=3)return 1;t=&i.operand[0];a=&i.operand[1];b=&i.operand[2];
if(t->type!=CDISASM_ARM_OPERAND_TILE||t->reg!=CDISASM_ARM_REG_ZA||t->base_reg!=CDISASM_ARM_REG_W8+r||t->imm!=o||t->register_list!=4||t->extend_type!=2||t->access!=CDISASM_OPERAND_ACCESS_READ_WRITE)return 1;
if(a->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||a->reg!=CDISASM_ARM_REG_Z0+z*4||a->register_list!=UINT16_C(0x0104)||a->extend_type!=2||a->access!=CDISASM_OPERAND_ACCESS_READ)return 1;
if(b->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||b->reg!=CDISASM_ARM_REG_Z0+m*4||b->register_list!=UINT16_C(0x0104)||b->extend_type!=2||b->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc1a11008),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{unsigned q,r,o,z,m;for(q=0;q<7;q++)for(r=0;r<4;r++)for(o=0;o<8;o++)for(z=0;z<16;z++)for(m=0;m<16;m++){
unsigned special=q>=4,wide=q==2||q==3||q>=5,u=q==1||q==3||q==6,ss=wide?2:1,ds=special?4:(wide?8:4);uint32_t base=special?(wide?UINT32_C(0xc1e01408):UINT32_C(0xc1a01408)):UINT32_C(0xc1a01400);uint32_t w=base|((!special&&wide)<<22)|(u<<4)|(r<<13)|o|(z<<6)|(m<<17);cdisasm_arm_name_id name=special&&!wide?CDISASM_ARM_NAME_USDOT:(u?CDISASM_ARM_NAME_UDOT:CDISASM_ARM_NAME_SDOT);unsigned form=special?(wide?4161+u:4160):4158+u;const cdisasm_arm_operand*t,*a,*b;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=name||i.form_id!=form||i.instruction_flags!=UINT32_C(0x05400000)||i.operand_count!=3)return 1;t=&i.operand[0];a=&i.operand[1];b=&i.operand[2];
if(t->type!=CDISASM_ARM_OPERAND_TILE||t->reg!=CDISASM_ARM_REG_ZA||t->base_reg!=CDISASM_ARM_REG_W8+r||t->imm!=o||t->register_list!=2||t->extend_type!=ds||t->access!=CDISASM_OPERAND_ACCESS_READ_WRITE)return 1;
if(a->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||a->reg!=CDISASM_ARM_REG_Z0+z*2||a->register_list!=UINT16_C(0x0102)||a->extend_type!=ss||a->access!=CDISASM_OPERAND_ACCESS_READ)return 1;
if(b->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||b->reg!=CDISASM_ARM_REG_Z0+m*2||b->register_list!=UINT16_C(0x0102)||b->extend_type!=ss||b->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc1a01400),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{unsigned q,r,o,z,m;for(q=0;q<7;q++)for(r=0;r<4;r++)for(o=0;o<8;o++)for(z=0;z<8;z++)for(m=0;m<8;m++){
unsigned special=q>=4,wide=q==2||q==3||q>=5,u=q==1||q==3||q==6,ss=wide?2:1,ds=special?4:(wide?8:4);uint32_t base=special?(wide?UINT32_C(0xc1e11408):UINT32_C(0xc1a11408)):UINT32_C(0xc1a11400);uint32_t w=base|((!special&&wide)<<22)|(u<<4)|(r<<13)|o|(z<<7)|(m<<18);cdisasm_arm_name_id name=special&&!wide?CDISASM_ARM_NAME_USDOT:(u?CDISASM_ARM_NAME_UDOT:CDISASM_ARM_NAME_SDOT);unsigned form=special?(wide?4201+u:4200):4198+u;const cdisasm_arm_operand*t,*a,*b;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=name||i.form_id!=form||i.instruction_flags!=UINT32_C(0x05400000)||i.operand_count!=3)return 1;t=&i.operand[0];a=&i.operand[1];b=&i.operand[2];
if(t->type!=CDISASM_ARM_OPERAND_TILE||t->reg!=CDISASM_ARM_REG_ZA||t->base_reg!=CDISASM_ARM_REG_W8+r||t->imm!=o||t->register_list!=4||t->extend_type!=ds||t->access!=CDISASM_OPERAND_ACCESS_READ_WRITE)return 1;
if(a->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||a->reg!=CDISASM_ARM_REG_Z0+z*4||a->register_list!=UINT16_C(0x0104)||a->extend_type!=ss||a->access!=CDISASM_OPERAND_ACCESS_READ)return 1;
if(b->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||b->reg!=CDISASM_ARM_REG_Z0+m*4||b->register_list!=UINT16_C(0x0104)||b->extend_type!=ss||b->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc1a11400),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{unsigned c,q,wid,r,o,z,m;for(c=2;c<=4;c+=2)for(q=0;q<2;q++)for(wid=0;wid<2;wid++)for(r=0;r<4;r++)for(o=0;o<8;o++)for(z=0;z<(c==4?8:16);z++)for(m=0;m<(c==4?8:16);m++){
unsigned sz=wid?8:4;uint32_t w=(c==4?UINT32_C(0xc1a11800):UINT32_C(0xc1a01800))|(wid<<22)|(q<<3)|(r<<13)|o|(z<<(c==4?7:6))|(m<<(c==4?18:17));const cdisasm_arm_operand*t,*a,*b;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=(q?CDISASM_ARM_NAME_FMLS:CDISASM_ARM_NAME_FMLA)||i.form_id!=(c==4?4203:4163)+q||i.instruction_flags!=UINT32_C(0x05402000)||i.operand_count!=3)return 1;t=&i.operand[0];a=&i.operand[1];b=&i.operand[2];
if(t->type!=CDISASM_ARM_OPERAND_TILE||t->reg!=CDISASM_ARM_REG_ZA||t->base_reg!=CDISASM_ARM_REG_W8+r||t->imm!=o||t->register_list!=c||t->extend_type!=sz||t->access!=CDISASM_OPERAND_ACCESS_READ_WRITE)return 1;
if(a->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||a->reg!=CDISASM_ARM_REG_Z0+z*c||a->register_list!=(uint16_t)(0x0100|c)||a->extend_type!=sz||a->access!=CDISASM_OPERAND_ACCESS_READ)return 1;
if(b->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||b->reg!=CDISASM_ARM_REG_Z0+m*c||b->register_list!=(uint16_t)(0x0100|c)||b->extend_type!=sz||b->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc1a01800),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{unsigned c,q,wid,r,o,z,m;for(c=2;c<=4;c+=2)for(q=0;q<2;q++)for(wid=0;wid<2;wid++)for(r=0;r<4;r++)for(o=0;o<8;o++)for(z=0;z<(c==4?8:16);z++)for(m=0;m<(c==4?8:16);m++){
unsigned sz=wid?8:4;uint32_t w=(c==4?UINT32_C(0xc1a11810):UINT32_C(0xc1a01810))|(wid<<22)|(q<<3)|(r<<13)|o|(z<<(c==4?7:6))|(m<<(c==4?18:17));const cdisasm_arm_operand*t,*a,*b;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=(q?CDISASM_ARM_NAME_SUB:CDISASM_ARM_NAME_ADD)||i.form_id!=(c==4?4205:4165)+q||i.instruction_flags!=UINT32_C(0x05400000)||i.operand_count!=3)return 1;t=&i.operand[0];a=&i.operand[1];b=&i.operand[2];
if(t->type!=CDISASM_ARM_OPERAND_TILE||t->reg!=CDISASM_ARM_REG_ZA||t->base_reg!=CDISASM_ARM_REG_W8+r||t->imm!=o||t->register_list!=c||t->extend_type!=sz||t->access!=CDISASM_OPERAND_ACCESS_READ_WRITE)return 1;
if(a->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||a->reg!=CDISASM_ARM_REG_Z0+z*c||a->register_list!=(uint16_t)(0x0100|c)||a->extend_type!=sz||a->access!=CDISASM_OPERAND_ACCESS_READ)return 1;
if(b->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||b->reg!=CDISASM_ARM_REG_Z0+m*c||b->register_list!=(uint16_t)(0x0100|c)||b->extend_type!=sz||b->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc1a01810),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{static const cdisasm_arm_name_id an[4]={CDISASM_ARM_NAME_FADD,CDISASM_ARM_NAME_FSUB,CDISASM_ARM_NAME_ADD,CDISASM_ARM_NAME_SUB};unsigned q,wid,r,o,z;for(q=0;q<4;q++)for(wid=0;wid<2;wid++)for(r=0;r<4;r++)for(o=0;o<8;o++)for(z=0;z<16;z++){
unsigned sz=wid?8:4;uint32_t w=UINT32_C(0xc1a01c00)|(wid<<22)|(q<<3)|(r<<13)|o|(z<<6);const cdisasm_arm_operand*t,*a;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=an[q]||i.form_id!=4167+q||i.instruction_flags!=(UINT32_C(0x05400000)|(q<2?CDISASM_ARM_INSTRUCTION_FLAG_FLOATING_POINT:0))||i.operand_count!=2)return 1;t=&i.operand[0];a=&i.operand[1];
if(t->type!=CDISASM_ARM_OPERAND_TILE||t->reg!=CDISASM_ARM_REG_ZA||t->base_reg!=CDISASM_ARM_REG_W8+r||t->imm!=o||t->register_list!=2||t->extend_type!=sz||t->access!=CDISASM_OPERAND_ACCESS_READ_WRITE)return 1;
if(a->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||a->reg!=CDISASM_ARM_REG_Z0+z*2||a->register_list!=UINT16_C(0x0102)||a->extend_type!=sz||a->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc1a01c00),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{static const cdisasm_arm_name_id an[4]={CDISASM_ARM_NAME_FADD,CDISASM_ARM_NAME_FSUB,CDISASM_ARM_NAME_ADD,CDISASM_ARM_NAME_SUB};unsigned q,wid,r,o,z;for(q=0;q<4;q++)for(wid=0;wid<2;wid++)for(r=0;r<4;r++)for(o=0;o<8;o++)for(z=0;z<8;z++){
unsigned sz=wid?8:4;uint32_t w=UINT32_C(0xc1a11c00)|(wid<<22)|(q<<3)|(r<<13)|o|(z<<7);const cdisasm_arm_operand*t,*a;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=an[q]||i.form_id!=4207+q||i.instruction_flags!=(UINT32_C(0x05400000)|(q<2?CDISASM_ARM_INSTRUCTION_FLAG_FLOATING_POINT:0))||i.operand_count!=2)return 1;t=&i.operand[0];a=&i.operand[1];
if(t->type!=CDISASM_ARM_OPERAND_TILE||t->reg!=CDISASM_ARM_REG_ZA||t->base_reg!=CDISASM_ARM_REG_W8+r||t->imm!=o||t->register_list!=4||t->extend_type!=sz||t->access!=CDISASM_OPERAND_ACCESS_READ_WRITE)return 1;
if(a->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||a->reg!=CDISASM_ARM_REG_Z0+z*4||a->register_list!=UINT16_C(0x0104)||a->extend_type!=sz||a->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc1a11c00),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{static const cdisasm_arm_name_id hn[4]={CDISASM_ARM_NAME_FADD,CDISASM_ARM_NAME_BFADD,CDISASM_ARM_NAME_FSUB,CDISASM_ARM_NAME_BFSUB};unsigned q,r,o,z;for(q=0;q<4;q++)for(r=0;r<4;r++)for(o=0;o<8;o++)for(z=0;z<16;z++){
uint32_t w=(q&1?UINT32_C(0xc1e41c00):UINT32_C(0xc1a41c00))|((q>>1)<<3)|(r<<13)|o|(z<<6);const cdisasm_arm_operand*t,*a;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=hn[q]||i.form_id!=4171+q||i.instruction_flags!=UINT32_C(0x05402000)||i.operand_count!=2)return 1;t=&i.operand[0];a=&i.operand[1];
if(t->type!=CDISASM_ARM_OPERAND_TILE||t->reg!=CDISASM_ARM_REG_ZA||t->base_reg!=CDISASM_ARM_REG_W8+r||t->imm!=o||t->register_list!=2||t->extend_type!=2||t->access!=CDISASM_OPERAND_ACCESS_READ_WRITE)return 1;
if(a->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||a->reg!=CDISASM_ARM_REG_Z0+z*2||a->register_list!=UINT16_C(0x0102)||a->extend_type!=2||a->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc1a41c00),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{static const cdisasm_arm_name_id hn[4]={CDISASM_ARM_NAME_FADD,CDISASM_ARM_NAME_BFADD,CDISASM_ARM_NAME_FSUB,CDISASM_ARM_NAME_BFSUB};unsigned q,r,o,z;for(q=0;q<4;q++)for(r=0;r<4;r++)for(o=0;o<8;o++)for(z=0;z<8;z++){
uint32_t w=(q&1?UINT32_C(0xc1e51c00):UINT32_C(0xc1a51c00))|((q>>1)<<3)|(r<<13)|o|(z<<7);const cdisasm_arm_operand*t,*a;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=hn[q]||i.form_id!=4211+q||i.instruction_flags!=UINT32_C(0x05402000)||i.operand_count!=2)return 1;t=&i.operand[0];a=&i.operand[1];
if(t->type!=CDISASM_ARM_OPERAND_TILE||t->reg!=CDISASM_ARM_REG_ZA||t->base_reg!=CDISASM_ARM_REG_W8+r||t->imm!=o||t->register_list!=4||t->extend_type!=2||t->access!=CDISASM_OPERAND_ACCESS_READ_WRITE)return 1;
if(a->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||a->reg!=CDISASM_ARM_REG_Z0+z*4||a->register_list!=UINT16_C(0x0104)||a->extend_type!=2||a->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc1a51c00),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{unsigned c,sz,d,p,n,m;for(c=2;c<=4;c+=2)for(sz=0;sz<4;sz++)for(d=0;d<32/c;d++)for(p=0;p<8;p++)for(n=0;n<32/c;n++)for(m=0;m<32/c;m++){
uint32_t w=(c==4?UINT32_C(0xc1218000):UINT32_C(0xc1208000))|(sz<<22)|(d*c)|(p<<10)|((n*c)<<5)|((m*c)<<16);const cdisasm_arm_operand*a,*b,*x,*y;unsigned es=1u<<sz;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=CDISASM_ARM_NAME_SEL||i.form_id!=(c==4?4216:4215)||i.instruction_flags!=UINT32_C(0x05c00000)||i.operand_count!=4)return 1;a=&i.operand[0];b=&i.operand[1];x=&i.operand[2];y=&i.operand[3];
if(a->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||a->reg!=CDISASM_ARM_REG_Z0+d*c||a->register_list!=(uint16_t)(0x0100|c)||a->extend_type!=es||a->access!=CDISASM_OPERAND_ACCESS_WRITE)return 1;
if(b->type!=CDISASM_ARM_OPERAND_PREDICATE||b->reg!=CDISASM_ARM_REG_PN8+p||b->extend_type!=es||b->flags!=CDISASM_ARM_OPERAND_FLAG_PREDICATE_TYPED||b->access!=CDISASM_OPERAND_ACCESS_READ)return 1;
if(x->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||x->reg!=CDISASM_ARM_REG_Z0+n*c||x->register_list!=(uint16_t)(0x0100|c)||x->extend_type!=es||x->access!=CDISASM_OPERAND_ACCESS_READ)return 1;
if(y->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||y->reg!=CDISASM_ARM_REG_Z0+m*c||y->register_list!=(uint16_t)(0x0100|c)||y->extend_type!=es||y->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc1208000),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{static const cdisasm_arm_name_id in[4]={CDISASM_ARM_NAME_SMAX,CDISASM_ARM_NAME_UMAX,CDISASM_ARM_NAME_SMIN,CDISASM_ARM_NAME_UMIN};static const unsigned iff[4]={4217,4219,4218,4220};unsigned q,sz,d,m;for(q=0;q<4;q++)for(sz=0;sz<4;sz++)for(d=0;d<16;d++)for(m=0;m<16;m++){
uint32_t w=UINT32_C(0xc120a000)|((q>>1)<<5)|(q&1)|(sz<<22)|(d<<1)|(m<<16);const cdisasm_arm_operand*a,*b,*s;unsigned es=1u<<sz;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=in[q]||i.form_id!=iff[q]||i.instruction_flags!=UINT32_C(0x05400000)||i.operand_count!=3)return 1;a=&i.operand[0];b=&i.operand[1];s=&i.operand[2];
if(a->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||a->reg!=CDISASM_ARM_REG_Z0+d*2||a->register_list!=UINT16_C(0x0102)||a->extend_type!=es||a->access!=CDISASM_OPERAND_ACCESS_WRITE)return 1;
if(b->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||b->reg!=CDISASM_ARM_REG_Z0+d*2||b->register_list!=UINT16_C(0x0102)||b->extend_type!=es||b->access!=CDISASM_OPERAND_ACCESS_READ)return 1;
if(s->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER||s->reg!=CDISASM_ARM_REG_Z0+m||s->extend_type!=es||s->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc120a000),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{static const cdisasm_arm_name_id fn[4]={CDISASM_ARM_NAME_FMAX,CDISASM_ARM_NAME_FMIN,CDISASM_ARM_NAME_FMAXNM,CDISASM_ARM_NAME_FMINNM},bn[4]={CDISASM_ARM_NAME_BFMAX,CDISASM_ARM_NAME_BFMIN,CDISASM_ARM_NAME_BFMAXNM,CDISASM_ARM_NAME_BFMINNM};static const unsigned ff[4]={4221,4223,4225,4227},bf[4]={4222,4224,4226,4228};unsigned q,sc,d,m;for(q=0;q<4;q++)for(sc=0;sc<4;sc++)for(d=0;d<16;d++)for(m=0;m<16;m++){
uint32_t w=UINT32_C(0xc120a100)|((q>>1)<<5)|(q&1)|(sc<<22)|(d<<1)|(m<<16);const cdisasm_arm_operand*a,*b,*s;unsigned es=sc?1u<<sc:2;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=(sc?fn[q]:bn[q])||i.form_id!=(sc?ff[q]:bf[q])||i.instruction_flags!=UINT32_C(0x05402000)||i.operand_count!=3)return 1;a=&i.operand[0];b=&i.operand[1];s=&i.operand[2];
if(a->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||a->reg!=CDISASM_ARM_REG_Z0+d*2||a->register_list!=UINT16_C(0x0102)||a->extend_type!=es||a->access!=CDISASM_OPERAND_ACCESS_WRITE)return 1;
if(b->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||b->reg!=CDISASM_ARM_REG_Z0+d*2||b->register_list!=UINT16_C(0x0102)||b->extend_type!=es||b->access!=CDISASM_OPERAND_ACCESS_READ)return 1;
if(s->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER||s->reg!=CDISASM_ARM_REG_Z0+m||s->extend_type!=es||s->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc120a100),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{static const uint32_t base[4]={UINT32_C(0xc120a220),UINT32_C(0xc120a221),UINT32_C(0xc120a300),UINT32_C(0xc120a400)};static const cdisasm_arm_name_id nn[4]={CDISASM_ARM_NAME_SRSHL,CDISASM_ARM_NAME_URSHL,CDISASM_ARM_NAME_ADD,CDISASM_ARM_NAME_SQDMULH};unsigned q,sz,d,m;for(q=0;q<4;q++)for(sz=0;sz<4;sz++)for(d=0;d<16;d++)for(m=0;m<16;m++){
uint32_t w=base[q]|(sz<<22)|(d<<1)|(m<<16);const cdisasm_arm_operand*a,*b,*s;unsigned es=1u<<sz;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=nn[q]||i.form_id!=4231+q||i.instruction_flags!=UINT32_C(0x05400000)||i.operand_count!=3)return 1;a=&i.operand[0];b=&i.operand[1];s=&i.operand[2];
if(a->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||a->reg!=CDISASM_ARM_REG_Z0+d*2||a->register_list!=UINT16_C(0x0102)||a->extend_type!=es||a->access!=CDISASM_OPERAND_ACCESS_WRITE)return 1;
if(b->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||b->reg!=CDISASM_ARM_REG_Z0+d*2||b->register_list!=UINT16_C(0x0102)||b->extend_type!=es||b->access!=CDISASM_OPERAND_ACCESS_READ)return 1;
if(s->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER||s->reg!=CDISASM_ARM_REG_Z0+m||s->extend_type!=es||s->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc120a220),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{static const cdisasm_arm_name_id in[4]={CDISASM_ARM_NAME_SMAX,CDISASM_ARM_NAME_UMAX,CDISASM_ARM_NAME_SMIN,CDISASM_ARM_NAME_UMIN};static const unsigned iff[4]={4235,4237,4236,4238};unsigned q,sz,d,m;for(q=0;q<4;q++)for(sz=0;sz<4;sz++)for(d=0;d<8;d++)for(m=0;m<16;m++){
uint32_t w=UINT32_C(0xc120a800)|((q>>1)<<5)|(q&1)|(sz<<22)|(d<<2)|(m<<16);const cdisasm_arm_operand*a,*b,*s;unsigned es=1u<<sz;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=in[q]||i.form_id!=iff[q]||i.instruction_flags!=UINT32_C(0x05400000)||i.operand_count!=3)return 1;a=&i.operand[0];b=&i.operand[1];s=&i.operand[2];
if(a->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||a->reg!=CDISASM_ARM_REG_Z0+d*4||a->register_list!=UINT16_C(0x0104)||a->extend_type!=es||a->access!=CDISASM_OPERAND_ACCESS_WRITE)return 1;
if(b->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||b->reg!=CDISASM_ARM_REG_Z0+d*4||b->register_list!=UINT16_C(0x0104)||b->extend_type!=es||b->access!=CDISASM_OPERAND_ACCESS_READ)return 1;
if(s->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER||s->reg!=CDISASM_ARM_REG_Z0+m||s->extend_type!=es||s->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc120a800),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{static const cdisasm_arm_name_id fn[4]={CDISASM_ARM_NAME_FMAX,CDISASM_ARM_NAME_FMIN,CDISASM_ARM_NAME_FMAXNM,CDISASM_ARM_NAME_FMINNM},bn[4]={CDISASM_ARM_NAME_BFMAX,CDISASM_ARM_NAME_BFMIN,CDISASM_ARM_NAME_BFMAXNM,CDISASM_ARM_NAME_BFMINNM};static const unsigned ff[4]={4239,4241,4243,4245},bf[4]={4240,4242,4244,4246};unsigned q,sc,d,m;for(q=0;q<4;q++)for(sc=0;sc<4;sc++)for(d=0;d<8;d++)for(m=0;m<16;m++){
uint32_t w=UINT32_C(0xc120a900)|((q>>1)<<5)|(q&1)|(sc<<22)|(d<<2)|(m<<16);const cdisasm_arm_operand*a,*b,*s;unsigned es=sc?1u<<sc:2;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=(sc?fn[q]:bn[q])||i.form_id!=(sc?ff[q]:bf[q])||i.instruction_flags!=UINT32_C(0x05402000)||i.operand_count!=3)return 1;a=&i.operand[0];b=&i.operand[1];s=&i.operand[2];
if(a->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||a->reg!=CDISASM_ARM_REG_Z0+d*4||a->register_list!=UINT16_C(0x0104)||a->extend_type!=es||a->access!=CDISASM_OPERAND_ACCESS_WRITE)return 1;
if(b->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||b->reg!=CDISASM_ARM_REG_Z0+d*4||b->register_list!=UINT16_C(0x0104)||b->extend_type!=es||b->access!=CDISASM_OPERAND_ACCESS_READ)return 1;
if(s->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER||s->reg!=CDISASM_ARM_REG_Z0+m||s->extend_type!=es||s->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc120a900),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{static const uint32_t base[4]={UINT32_C(0xc120aa20),UINT32_C(0xc120aa21),UINT32_C(0xc120ab00),UINT32_C(0xc120ac00)};static const cdisasm_arm_name_id nn[4]={CDISASM_ARM_NAME_SRSHL,CDISASM_ARM_NAME_URSHL,CDISASM_ARM_NAME_ADD,CDISASM_ARM_NAME_SQDMULH};unsigned q,sz,d,m;for(q=0;q<4;q++)for(sz=0;sz<4;sz++)for(d=0;d<8;d++)for(m=0;m<16;m++){
uint32_t w=base[q]|(sz<<22)|(d<<2)|(m<<16);const cdisasm_arm_operand*a,*b,*s;unsigned es=1u<<sz;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=nn[q]||i.form_id!=4249+q||i.instruction_flags!=UINT32_C(0x05400000)||i.operand_count!=3)return 1;a=&i.operand[0];b=&i.operand[1];s=&i.operand[2];
if(a->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||a->reg!=CDISASM_ARM_REG_Z0+d*4||a->register_list!=UINT16_C(0x0104)||a->extend_type!=es||a->access!=CDISASM_OPERAND_ACCESS_WRITE)return 1;
if(b->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||b->reg!=CDISASM_ARM_REG_Z0+d*4||b->register_list!=UINT16_C(0x0104)||b->extend_type!=es||b->access!=CDISASM_OPERAND_ACCESS_READ)return 1;
if(s->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER||s->reg!=CDISASM_ARM_REG_Z0+m||s->extend_type!=es||s->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc120aa20),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{static const cdisasm_arm_name_id in[4]={CDISASM_ARM_NAME_SMAX,CDISASM_ARM_NAME_UMAX,CDISASM_ARM_NAME_SMIN,CDISASM_ARM_NAME_UMIN};static const unsigned iff[4]={4253,4255,4254,4256};unsigned q,sz,d,m;for(q=0;q<4;q++)for(sz=0;sz<4;sz++)for(d=0;d<16;d++)for(m=0;m<16;m++){
uint32_t w=UINT32_C(0xc120b000)|((q>>1)<<5)|(q&1)|(sz<<22)|(d<<1)|(m<<17);const cdisasm_arm_operand*a,*b,*s;unsigned es=1u<<sz;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=in[q]||i.form_id!=iff[q]||i.instruction_flags!=UINT32_C(0x05400000)||i.operand_count!=3)return 1;a=&i.operand[0];b=&i.operand[1];s=&i.operand[2];
if(a->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||a->reg!=CDISASM_ARM_REG_Z0+d*2||a->register_list!=UINT16_C(0x0102)||a->extend_type!=es||a->access!=CDISASM_OPERAND_ACCESS_WRITE)return 1;
if(b->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||b->reg!=CDISASM_ARM_REG_Z0+d*2||b->register_list!=UINT16_C(0x0102)||b->extend_type!=es||b->access!=CDISASM_OPERAND_ACCESS_READ)return 1;
if(s->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||s->reg!=CDISASM_ARM_REG_Z0+m*2||s->register_list!=UINT16_C(0x0102)||s->extend_type!=es||s->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc120b000),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{static const cdisasm_arm_name_id fn[4]={CDISASM_ARM_NAME_FMAX,CDISASM_ARM_NAME_FMIN,CDISASM_ARM_NAME_FMAXNM,CDISASM_ARM_NAME_FMINNM},bn[4]={CDISASM_ARM_NAME_BFMAX,CDISASM_ARM_NAME_BFMIN,CDISASM_ARM_NAME_BFMAXNM,CDISASM_ARM_NAME_BFMINNM};static const unsigned ff[4]={4257,4259,4261,4263},bf[4]={4258,4260,4262,4264};unsigned q,sc,d,m;for(q=0;q<4;q++)for(sc=0;sc<4;sc++)for(d=0;d<16;d++)for(m=0;m<16;m++){
uint32_t w=UINT32_C(0xc120b100)|((q>>1)<<5)|(q&1)|(sc<<22)|(d<<1)|(m<<17);const cdisasm_arm_operand*a,*b,*s;unsigned es=sc?1u<<sc:2;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=(sc?fn[q]:bn[q])||i.form_id!=(sc?ff[q]:bf[q])||i.instruction_flags!=UINT32_C(0x05402000)||i.operand_count!=3)return 1;a=&i.operand[0];b=&i.operand[1];s=&i.operand[2];
if(a->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||a->reg!=CDISASM_ARM_REG_Z0+d*2||a->register_list!=UINT16_C(0x0102)||a->extend_type!=es||a->access!=CDISASM_OPERAND_ACCESS_WRITE)return 1;
if(b->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||b->reg!=CDISASM_ARM_REG_Z0+d*2||b->register_list!=UINT16_C(0x0102)||b->extend_type!=es||b->access!=CDISASM_OPERAND_ACCESS_READ)return 1;
if(s->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||s->reg!=CDISASM_ARM_REG_Z0+m*2||s->register_list!=UINT16_C(0x0102)||s->extend_type!=es||s->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc120b100),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{static const uint32_t base[3]={UINT32_C(0xc120b220),UINT32_C(0xc120b221),UINT32_C(0xc120b400)};static const cdisasm_arm_name_id nn[3]={CDISASM_ARM_NAME_SRSHL,CDISASM_ARM_NAME_URSHL,CDISASM_ARM_NAME_SQDMULH};unsigned q,sz,d,m;for(q=0;q<3;q++)for(sz=0;sz<4;sz++)for(d=0;d<16;d++)for(m=0;m<16;m++){
uint32_t w=base[q]|(sz<<22)|(d<<1)|(m<<17);const cdisasm_arm_operand*a,*b,*s;unsigned es=1u<<sz;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=nn[q]||i.form_id!=4269+q||i.instruction_flags!=UINT32_C(0x05400000)||i.operand_count!=3)return 1;a=&i.operand[0];b=&i.operand[1];s=&i.operand[2];
if(a->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||a->reg!=CDISASM_ARM_REG_Z0+d*2||a->register_list!=UINT16_C(0x0102)||a->extend_type!=es||a->access!=CDISASM_OPERAND_ACCESS_WRITE)return 1;
if(b->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||b->reg!=CDISASM_ARM_REG_Z0+d*2||b->register_list!=UINT16_C(0x0102)||b->extend_type!=es||b->access!=CDISASM_OPERAND_ACCESS_READ)return 1;
if(s->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||s->reg!=CDISASM_ARM_REG_Z0+m*2||s->register_list!=UINT16_C(0x0102)||s->extend_type!=es||s->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc120b220),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{static const cdisasm_arm_name_id in[4]={CDISASM_ARM_NAME_SMAX,CDISASM_ARM_NAME_UMAX,CDISASM_ARM_NAME_SMIN,CDISASM_ARM_NAME_UMIN};static const unsigned iff[4]={4272,4274,4273,4275};unsigned q,sz,d,m;for(q=0;q<4;q++)for(sz=0;sz<4;sz++)for(d=0;d<8;d++)for(m=0;m<8;m++){
uint32_t w=UINT32_C(0xc120b800)|((q>>1)<<5)|(q&1)|(sz<<22)|(d<<2)|(m<<18);const cdisasm_arm_operand*a,*b,*s;unsigned es=1u<<sz;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=in[q]||i.form_id!=iff[q]||i.instruction_flags!=UINT32_C(0x05400000)||i.operand_count!=3)return 1;a=&i.operand[0];b=&i.operand[1];s=&i.operand[2];
if(a->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||a->reg!=CDISASM_ARM_REG_Z0+d*4||a->register_list!=UINT16_C(0x0104)||a->extend_type!=es||a->access!=CDISASM_OPERAND_ACCESS_WRITE)return 1;
if(b->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||b->reg!=CDISASM_ARM_REG_Z0+d*4||b->register_list!=UINT16_C(0x0104)||b->extend_type!=es||b->access!=CDISASM_OPERAND_ACCESS_READ)return 1;
if(s->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||s->reg!=CDISASM_ARM_REG_Z0+m*4||s->register_list!=UINT16_C(0x0104)||s->extend_type!=es||s->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc120b800),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{static const cdisasm_arm_name_id fn[4]={CDISASM_ARM_NAME_FMAX,CDISASM_ARM_NAME_FMIN,CDISASM_ARM_NAME_FMAXNM,CDISASM_ARM_NAME_FMINNM},bn[4]={CDISASM_ARM_NAME_BFMAX,CDISASM_ARM_NAME_BFMIN,CDISASM_ARM_NAME_BFMAXNM,CDISASM_ARM_NAME_BFMINNM};static const unsigned ff[4]={4276,4278,4280,4282},bf[4]={4277,4279,4281,4283};unsigned q,sc,d,m;for(q=0;q<4;q++)for(sc=0;sc<4;sc++)for(d=0;d<8;d++)for(m=0;m<8;m++){
uint32_t w=UINT32_C(0xc120b900)|((q>>1)<<5)|(q&1)|(sc<<22)|(d<<2)|(m<<18);const cdisasm_arm_operand*a,*b,*s;unsigned es=sc?1u<<sc:2;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=(sc?fn[q]:bn[q])||i.form_id!=(sc?ff[q]:bf[q])||i.instruction_flags!=UINT32_C(0x05402000)||i.operand_count!=3)return 1;a=&i.operand[0];b=&i.operand[1];s=&i.operand[2];
if(a->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||a->reg!=CDISASM_ARM_REG_Z0+d*4||a->register_list!=UINT16_C(0x0104)||a->extend_type!=es||a->access!=CDISASM_OPERAND_ACCESS_WRITE)return 1;
if(b->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||b->reg!=CDISASM_ARM_REG_Z0+d*4||b->register_list!=UINT16_C(0x0104)||b->extend_type!=es||b->access!=CDISASM_OPERAND_ACCESS_READ)return 1;
if(s->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||s->reg!=CDISASM_ARM_REG_Z0+m*4||s->register_list!=UINT16_C(0x0104)||s->extend_type!=es||s->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}
if(dw(UINT32_C(0xc120b900),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{static const uint32_t base[3]={UINT32_C(0xc120ba20),UINT32_C(0xc120ba21),UINT32_C(0xc120bc00)};static const cdisasm_arm_name_id nn[3]={CDISASM_ARM_NAME_SRSHL,CDISASM_ARM_NAME_URSHL,CDISASM_ARM_NAME_SQDMULH};unsigned q,sz,d,m;for(q=0;q<3;q++)for(sz=0;sz<4;sz++)for(d=0;d<8;d++)for(m=0;m<8;m++){uint32_t w=base[q]|(sz<<22)|(d<<2)|(m<<18);const cdisasm_arm_operand*a,*b,*s;unsigned es=1u<<sz;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=nn[q]||i.form_id!=4288+q||i.instruction_flags!=UINT32_C(0x05400000)||i.operand_count!=3)return 1;a=&i.operand[0];b=&i.operand[1];s=&i.operand[2];if(a->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||a->reg!=CDISASM_ARM_REG_Z0+d*4||a->register_list!=UINT16_C(0x0104)||a->extend_type!=es||a->access!=CDISASM_OPERAND_ACCESS_WRITE)return 1;if(b->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||b->reg!=CDISASM_ARM_REG_Z0+d*4||b->register_list!=UINT16_C(0x0104)||b->extend_type!=es||b->access!=CDISASM_OPERAND_ACCESS_READ)return 1;if(s->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||s->reg!=CDISASM_ARM_REG_Z0+m*4||s->register_list!=UINT16_C(0x0104)||s->extend_type!=es||s->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}if(dw(UINT32_C(0xc120ba20),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{unsigned c,u,sz,d,n,m;for(c=2;c<=4;c+=2)for(u=0;u<2;u++)for(sz=0;sz<4;sz++)for(d=0;d<32/c;d++)for(n=0;n<32;n++)for(m=0;m<32;m++){uint32_t w=(c==4?UINT32_C(0xc120cc00):UINT32_C(0xc120c400))|u|(sz<<22)|(d*c)|(n<<5)|(m<<16);const cdisasm_arm_operand*a,*b,*s;unsigned es=1u<<sz;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=(u?CDISASM_ARM_NAME_UCLAMP:CDISASM_ARM_NAME_SCLAMP)||i.form_id!=(c==4?4297:4293)+u||i.instruction_flags!=UINT32_C(0x05400000)||i.operand_count!=3)return 1;a=&i.operand[0];b=&i.operand[1];s=&i.operand[2];if(a->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||a->reg!=CDISASM_ARM_REG_Z0+d*c||a->register_list!=(uint16_t)(0x0100|c)||a->extend_type!=es||a->access!=CDISASM_OPERAND_ACCESS_WRITE)return 1;if(b->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER||b->reg!=CDISASM_ARM_REG_Z0+n||b->extend_type!=es||b->access!=CDISASM_OPERAND_ACCESS_READ)return 1;if(s->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER||s->reg!=CDISASM_ARM_REG_Z0+m||s->extend_type!=es||s->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}if(dw(UINT32_C(0xc120c400),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{unsigned q,u,sz,d,n,m;for(q=0;q<2;q++)for(u=0;u<2;u++)for(sz=0;sz<(q?1u:4u);sz++)for(d=0;d<16;d++)for(n=0;n<32;n++)for(m=0;m<32;m++){uint32_t w=(q?UINT32_C(0xc120d400):UINT32_C(0xc120d000))|u|(q?0:sz<<22)|(d*2)|(n<<5)|(m<<16);const cdisasm_arm_operand*a,*b,*s;unsigned es=q?16u:1u<<sz;if(dw(w,CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=(u?CDISASM_ARM_NAME_UZP:CDISASM_ARM_NAME_ZIP)||i.form_id!=(q?4301:4299)+u||i.instruction_flags!=UINT32_C(0x05400000)||i.operand_count!=3)return 1;a=&i.operand[0];b=&i.operand[1];s=&i.operand[2];if(a->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||a->reg!=CDISASM_ARM_REG_Z0+d*2||a->register_list!=UINT16_C(0x0102)||a->extend_type!=es||a->access!=CDISASM_OPERAND_ACCESS_WRITE)return 1;if(b->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER||b->reg!=CDISASM_ARM_REG_Z0+n||b->extend_type!=es||b->access!=CDISASM_OPERAND_ACCESS_READ)return 1;if(s->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER||s->reg!=CDISASM_ARM_REG_Z0+m||s->extend_type!=es||s->access!=CDISASM_OPERAND_ACCESS_READ)return 1;}if(dw(UINT32_C(0xc120d000),CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
#if USE_DISASM_FORMAT
{char t[160];if(dw(UINT32_C(0xc19fffaf),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"fmlal za.h[w11, 6:7, vgx4], {z28.b, z29.b, z30.b, z31.b}, z15.b[15]"))return 1;}
{char t[160];if(dw(UINT32_C(0xc19fff9b),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"bfmlsl za.s[w11, 6:7, vgx4], {z28.h, z29.h, z30.h, z31.h}, z15.h[6]"))return 1;}
{char t[144];if(dw(UINT32_C(0xc19f7fdb),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"bfmlsl za.s[w11, 6:7, vgx2], {z30.h, z31.h}, z15.h[6]"))return 1;}
{char t[112];if(dw(UINT32_C(0xc1cfefeb),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"fmlal za.h[w11, 6:7], z31.b, z15.b[15]"))return 1;}
{char t[112];if(dw(UINT32_C(0xc184bc69),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"fmlsl za.s[w9, 2:3], z3.h, z4.h[7]"))return 1;}
{char t[96];if(dw(UINT32_C(0xc1cfffe7),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"smlal za.s[w11, 14:15], z31.h, z15.h[7]"))return 1;i.form_id=3956;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[112];if(dw(UINT32_C(0xc117392b),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"bfmla za.h[w9, 3, vgx2], {z8.h, z9.h}, z7.h[5]"))return 1;i.form_id=3965;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[144];if(dw(UINT32_C(0xc113ff35),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"bfmls za.h[w11, 5, vgx4], {z24.h, z25.h, z26.h, z27.h}, z3.h[6]"))return 1;i.form_id=4013;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[144];if(dw(UINT32_C(0xc1d3ff19),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"umlsl za.s[w11, 2:3, vgx4], {z24.h, z25.h, z26.h, z27.h}, z3.h[6]"))return 1;i.form_id=4048;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[128];if(dw(UINT32_C(0xc1d7390e),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"smlsl za.s[w9, 4:5, vgx2], {z8.h, z9.h}, z7.h[5]"))return 1;i.form_id=4000;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[128];if(dw(UINT32_C(0xc1d3671d),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"udot za.d[w11, 5, vgx2], {z24.h, z25.h}, z3.h[1]"))return 1;i.form_id=3996;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[144];if(dw(UINT32_C(0xc1d3e71d),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"udot za.d[w11, 5, vgx4], {z24.h, z25.h, z26.h, z27.h}, z3.h[1]"))return 1;i.form_id=4042;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[144];if(dw(UINT32_C(0xc1d7ad1b),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"uvdot za.d[w9, 3, vgx4], {z8.h, z9.h, z10.h, z11.h}, z7.h[1]"))return 1;i.form_id=4044;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[144];if(dw(UINT32_C(0xc153eb35),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"uvdot za.s[w11, 5, vgx4], {z24.b, z25.b, z26.b, z27.b}, z3.b[2]"))return 1;i.form_id=4020;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[144];if(dw(UINT32_C(0xc153fb3d),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"sudot za.s[w11, 5, vgx4], {z24.b, z25.b, z26.b, z27.b}, z3.b[2]"))return 1;i.form_id=4026;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[192];if(dw(UINT32_C(0xc1fd6b1b),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"umlsl za.s[w11, 6:7, vgx4], {z24.h, z25.h, z26.h, z27.h}, {z28.h, z29.h, z30.h, z31.h}"))return 1;i.form_id=4186;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[160];if(dw(UINT32_C(0xc1fc6bdb),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"umlsl za.s[w11, 6:7, vgx2], {z30.h, z31.h}, {z28.h, z29.h}"))return 1;i.form_id=4146;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[160];if(dw(UINT32_C(0xc1fc73df),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"bfmls za.h[w11, 7, vgx2], {z30.h, z31.h}, {z28.h, z29.h}"))return 1;i.form_id=4154;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[192];if(dw(UINT32_C(0xc1f9739f),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"bfmls za.h[w11, 7, vgx4], {z28.h, z29.h, z30.h, z31.h}, {z24.h, z25.h, z26.h, z27.h}"))return 1;i.form_id=4194;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[160];if(dw(UINT32_C(0xc1ea3501),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"sdot za.d[w9, 1, vgx2], {z8.h, z9.h}, {z10.h, z11.h}"))return 1;i.form_id=4159;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[160];if(dw(UINT32_C(0xc1bc77cf),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"usdot za.s[w11, 7, vgx2], {z30.b, z31.b}, {z28.b, z29.b}"))return 1;i.form_id=4158;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[192];if(dw(UINT32_C(0xc1ed3501),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"sdot za.d[w9, 1, vgx4], {z8.h, z9.h, z10.h, z11.h}, {z12.h, z13.h, z14.h, z15.h}"))return 1;i.form_id=4199;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[192];if(dw(UINT32_C(0xc1b9778f),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"usdot za.s[w11, 7, vgx4], {z28.b, z29.b, z30.b, z31.b}, {z24.b, z25.b, z26.b, z27.b}"))return 1;i.form_id=4198;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[192];if(dw(UINT32_C(0xc1f97b8f),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"fmls za.d[w11, 7, vgx4], {z28.d, z29.d, z30.d, z31.d}, {z24.d, z25.d, z26.d, z27.d}"))return 1;i.form_id=4203;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[192];if(dw(UINT32_C(0xc1f97b9f),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"sub za.d[w11, 7, vgx4], {z28.d, z29.d, z30.d, z31.d}, {z24.d, z25.d, z26.d, z27.d}"))return 1;i.form_id=4205;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[128];if(dw(UINT32_C(0xc1e07fdf),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"sub za.d[w11, 7, vgx2], {z30.d, z31.d}"))return 1;i.form_id=4167;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[160];if(dw(UINT32_C(0xc1e17f9f),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"sub za.d[w11, 7, vgx4], {z28.d, z29.d, z30.d, z31.d}"))return 1;i.form_id=4207;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[128];if(dw(UINT32_C(0xc1e47fcf),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"bfsub za.h[w11, 7, vgx2], {z30.h, z31.h}"))return 1;i.form_id=4171;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[160];if(dw(UINT32_C(0xc1e57f8f),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"bfsub za.h[w11, 7, vgx4], {z28.h, z29.h, z30.h, z31.h}"))return 1;i.form_id=4211;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[256];if(dw(UINT32_C(0xc1f59f1c),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"sel {z28.d, z29.d, z30.d, z31.d}, pn15, {z24.d, z25.d, z26.d, z27.d}, {z20.d, z21.d, z22.d, z23.d}"))return 1;i.form_id=4215;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[160];if(dw(UINT32_C(0xc16fa03f),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"umin {z30.h, z31.h}, {z30.h, z31.h}, z15.h"))return 1;i.form_id=4217;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[176];if(dw(UINT32_C(0xc12fa13f),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"bfminnm {z30.h, z31.h}, {z30.h, z31.h}, z15.h"))return 1;i.form_id=4221;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[176];if(dw(UINT32_C(0xc1efa41e),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"sqdmulh {z30.d, z31.d}, {z30.d, z31.d}, z15.d"))return 1;i.form_id=4231;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[224];if(dw(UINT32_C(0xc1efa83d),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"umin {z28.d, z29.d, z30.d, z31.d}, {z28.d, z29.d, z30.d, z31.d}, z15.d"))return 1;i.form_id=4235;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[224];if(dw(UINT32_C(0xc12fa93d),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"bfminnm {z28.h, z29.h, z30.h, z31.h}, {z28.h, z29.h, z30.h, z31.h}, z15.h"))return 1;i.form_id=4239;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[224];if(dw(UINT32_C(0xc1efac1c),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"sqdmulh {z28.d, z29.d, z30.d, z31.d}, {z28.d, z29.d, z30.d, z31.d}, z15.d"))return 1;i.form_id=4249;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[224];if(dw(UINT32_C(0xc1fcb03f),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"umin {z30.d, z31.d}, {z30.d, z31.d}, {z28.d, z29.d}"))return 1;i.form_id=4253;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[224];if(dw(UINT32_C(0xc13cb13f),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"bfminnm {z30.h, z31.h}, {z30.h, z31.h}, {z28.h, z29.h}"))return 1;i.form_id=4257;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[224];if(dw(UINT32_C(0xc1fcb41e),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"sqdmulh {z30.d, z31.d}, {z30.d, z31.d}, {z28.d, z29.d}"))return 1;i.form_id=4269;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[256];if(dw(UINT32_C(0xc1f8b83d),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"umin {z28.d, z29.d, z30.d, z31.d}, {z28.d, z29.d, z30.d, z31.d}, {z24.d, z25.d, z26.d, z27.d}"))return 1;i.form_id=4272;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{char t[256];if(dw(UINT32_C(0xc138b93d),CDISASM_ARM_CPU_ANY,&i)!=4||!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,"bfminnm {z28.h, z29.h, z30.h, z31.h}, {z28.h, z29.h, z30.h, z31.h}, {z24.h, z25.h, z26.h, z27.h}"))return 1;i.form_id=4276;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}
{static const uint32_t words[3]={UINT32_C(0xc12f6bdb),UINT32_C(0xc12f6fff),UINT32_C(0xc13f6b9b)};static const uint16_t forms[3]={4067,4075,4110};static const char*texts[3]={"bfmlsl za.s[w11, 6:7, vgx2], {z30.h, z31.h}, z15.h","bfmlsl za.s[w11, 14:15], z31.h, z15.h","bfmlsl za.s[w11, 6:7, vgx4], {z28.h, z29.h, z30.h, z31.h}, z15.h"};unsigned q;for(q=0;q<3;q++){char t[192];const cdisasm_arm_operand*a,*b,*c;if(dw(words[q],CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=CDISASM_ARM_NAME_BFMLSL||i.form_id!=forms[q]||i.instruction_flags!=UINT32_C(0x05402000)||i.operand_count!=3)return 1;a=&i.operand[0];b=&i.operand[1];c=&i.operand[2];if(a->type!=CDISASM_ARM_OPERAND_TILE||a->reg!=CDISASM_ARM_REG_ZA||a->base_reg!=CDISASM_ARM_REG_W11||a->imm!=(q==1?14:6)||a->register_list!=(q==2?4:2)||a->extend_type!=4||a->access!=CDISASM_OPERAND_ACCESS_READ_WRITE)return 1;if(b->extend_type!=2||b->access!=CDISASM_OPERAND_ACCESS_READ||c->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER||c->reg!=CDISASM_ARM_REG_Z15||c->extend_type!=2||c->access!=CDISASM_OPERAND_ACCESS_READ)return 1;if(!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,texts[q]))return 1;i.form_id++;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}if(dw(words[0],CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{static const uint32_t words[3]={UINT32_C(0xc1220804),UINT32_C(0xc13f6b87),UINT32_C(0xc13f6fe7)};static const uint16_t forms[3]={4066,4109,4116};static const char*texts[3]={"fmlal za.h[w8, 0:1, vgx2], {z0.b, z1.b}, z2.b","fmlal za.h[w11, 6:7, vgx4], {z28.b, z29.b, z30.b, z31.b}, z15.b","fmlal za.h[w11, 14:15], z31.b, z15.b"};unsigned q;for(q=0;q<3;q++){char t[192];const cdisasm_arm_operand*a,*b,*c;if(dw(words[q],CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=CDISASM_ARM_NAME_FMLAL||i.form_id!=forms[q]||i.instruction_flags!=UINT32_C(0x05402000)||i.operand_count!=3)return 1;a=&i.operand[0];b=&i.operand[1];c=&i.operand[2];if(a->type!=CDISASM_ARM_OPERAND_TILE||a->reg!=CDISASM_ARM_REG_ZA||a->imm!=(q==2?14:q==1?6:0)||a->register_list!=(q==1?4:2)||a->extend_type!=2||a->access!=CDISASM_OPERAND_ACCESS_READ_WRITE||b->extend_type!=1||b->access!=CDISASM_OPERAND_ACCESS_READ||c->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER||c->extend_type!=1||c->access!=CDISASM_OPERAND_ACCESS_READ)return 1;if(!cdisasm_arm_format(&i,0,t,sizeof(t))||strcmp(t,texts[q]))return 1;i.form_id++;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}if(dw(words[0],CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
{static const uint32_t words[4]={UINT32_C(0xc1bc6bdb),UINT32_C(0xc1b96b9b),UINT32_C(0xc1bc6be3),UINT32_C(0xc1b96ba3)};static const uint16_t forms[4]={4143,4183,4145,4185};static const cdisasm_arm_name_id names[4]={CDISASM_ARM_NAME_BFMLSL,CDISASM_ARM_NAME_BFMLSL,CDISASM_ARM_NAME_FMLAL,CDISASM_ARM_NAME_FMLAL};unsigned q;for(q=0;q<4;q++){char t[224];const cdisasm_arm_operand*a,*b,*c;unsigned count=(q&1)?4:2,size=q<2?2:1;if(dw(words[q],CDISASM_ARM_CPU_ANY,&i)!=4||i.name_id!=names[q]||i.form_id!=forms[q]||i.instruction_flags!=UINT32_C(0x05402000)||i.operand_count!=3)return 1;a=&i.operand[0];b=&i.operand[1];c=&i.operand[2];if(a->type!=CDISASM_ARM_OPERAND_TILE||a->reg!=CDISASM_ARM_REG_ZA||a->base_reg!=CDISASM_ARM_REG_W11||a->imm!=6||a->register_list!=count||a->extend_type!=(q<2?4:2)||a->access!=CDISASM_OPERAND_ACCESS_READ_WRITE)return 1;if(b->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||b->reg!=CDISASM_ARM_REG_Z0+(count==4?28:30)||b->register_list!=(uint16_t)(0x0100|count)||b->extend_type!=size||b->access!=CDISASM_OPERAND_ACCESS_READ||c->type!=CDISASM_ARM_OPERAND_SCALABLE_REGISTER_LIST||c->reg!=CDISASM_ARM_REG_Z0+(count==4?24:28)||c->register_list!=(uint16_t)(0x0100|count)||c->extend_type!=size||c->access!=CDISASM_OPERAND_ACCESS_READ)return 1;if(!cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;i.form_id++;if(cdisasm_arm_format(&i,0,t,sizeof(t)))return 1;}if(dw(words[0],CDISASM_ARM_CPU_CORTEX_A53,&i)!=0||i.last_error_id!=CDISASM_STATUS_INVALID_INSTRUCTION)return 1;}
#endif
#else
if(dw(UINT32_C(0xc1c01000),CDISASM_ARM_CPU_ANY,&i)!=0||i.last_error_id!=CDISASM_STATUS_UNSUPPORTED_INSTRUCTION)return 1;
#endif
puts("ARM SME indexed matrix tests passed (160 exact leaves)");return 0;}
