#ifndef CDISASM_CDISASM_X86_H
#define CDISASM_CDISASM_X86_H

#include "cdisasm_common.h"

#if !USE_ARCH_X86
#  error "cdisasm x86 support is disabled in this build"
#endif

#include "cdisasm_x86_ids.h"

#if defined(_WIN32) || defined(__CYGWIN__)
#  if defined(CDISASM_STATIC) || defined(CDISASM_X86_STATIC)
#    define CDISASM_X86_API
#  elif defined(CDISASM_BUILDING_LIBRARY) \
        || defined(CDISASM_X86_BUILDING_LIBRARY)
#    define CDISASM_X86_API __declspec(dllexport)
#  else
#    define CDISASM_X86_API __declspec(dllimport)
#  endif
#elif defined(__GNUC__) || defined(__clang__)
#  if defined(CDISASM_STATIC) || defined(CDISASM_X86_STATIC)
#    define CDISASM_X86_API __attribute__((visibility("hidden")))
#  else
#    define CDISASM_X86_API __attribute__((visibility("default")))
#  endif
#else
#  define CDISASM_X86_API
#endif

#ifdef __cplusplus
extern "C" {
#endif

#define CDISASM_MAX_INSTRUCTION_SIZE 15
/* VPERMIL2 has four explicit vector operands plus an imm8 operand. */
#define CDISASM_MAX_OPERANDS 5
#define CDISASM_MAX_X86_GROUPS 15
#define CDISASM_OPCODE_SIZE 32
#define CDISASM_X86_ENCODING_SIZE 16
#define CDISASM_INSTRUCTION_SIZE 248

/**
 * Numeric canonical XED IFORM identifier used by generated fallback rows.
 * Zero means that no generated form identity is attached.  The identifier is
 * metadata only: decoding and CPU/runtime-family validation remain native to
 * cdisasm and never depend on XED at run time.
 */
typedef uint16_t cdisasm_x86_form_id;
#define CDISASM_X86_FORM_NONE UINT16_C(0)
/**
 * Operand byte-size sentinel for architecturally variable or opaque storage.
 *
 * This is used by XSAVE-family memory operands, whose exact state-area size is
 * selected at run time, and by AMX tile registers, whose active dimensions are
 * selected by TILECFG.  It never denotes a 255-byte scalar operand.
 */
#define CDISASM_X86_OPERAND_SIZE_VARIABLE UINT8_MAX

/** x86 execution mode. Values are fixed-width across the DLL boundary. */
typedef uint32_t cdisasm_mode;
#define CDISASM_MODE_16 UINT32_C(16)
#define CDISASM_MODE_32 UINT32_C(32)
#define CDISASM_MODE_64 UINT32_C(64)
typedef cdisasm_mode cdisasm_x86_mode;
#define CDISASM_X86_MODE_16 CDISASM_MODE_16
#define CDISASM_X86_MODE_32 CDISASM_MODE_32
#define CDISASM_X86_MODE_64 CDISASM_MODE_64

/** Bit mask returned by cdisasm_x86_cpu_mode_mask. */
typedef uint32_t cdisasm_x86_mode_mask;
#define CDISASM_X86_MODE_MASK_NONE UINT32_C(0x00)
#define CDISASM_X86_MODE_MASK_16 UINT32_C(0x01)
#define CDISASM_X86_MODE_MASK_32 UINT32_C(0x02)
#define CDISASM_X86_MODE_MASK_64 UINT32_C(0x04)

/**
 * Stable x86 family IDs.  The list contains both direct ISA families
 * (SSE2, FMA3, AES, ...) and validation families for catalog forms whose
 * encoding is exact but whose CPU, mode, privilege, vendor, or operand
 * legality is family-specific.  These IDs are deliberately separate from
 * cdisasm_x86_group_id: ISA groups describe instruction-set membership,
 * while families provide a compact runtime selection surface.
 */
typedef uint16_t cdisasm_x86_family_id;
#define CDISASM_X86_FAMILY_NONE UINT16_C(0)
#define CDISASM_X86_FAMILY_AVX512_EVEX UINT16_C(1)
#define CDISASM_X86_FAMILY_APX_EVEX UINT16_C(2)
#define CDISASM_X86_FAMILY_AVX2_GATHER UINT16_C(3)
#define CDISASM_X86_FAMILY_FRED UINT16_C(4)
#define CDISASM_X86_FAMILY_TDX UINT16_C(5)
#define CDISASM_X86_FAMILY_VIA_PADLOCK UINT16_C(6)
#define CDISASM_X86_FAMILY_X87 UINT16_C(7)
#define CDISASM_X86_FAMILY_MOVRS UINT16_C(8)
#define CDISASM_X86_FAMILY_INTEL_VMX UINT16_C(9)
#define CDISASM_X86_FAMILY_AMD_SVM UINT16_C(10)
#define CDISASM_X86_FAMILY_MMX UINT16_C(11)
#define CDISASM_X86_FAMILY_3DNOW UINT16_C(12)
#define CDISASM_X86_FAMILY_SSE UINT16_C(13)
#define CDISASM_X86_FAMILY_SSE2 UINT16_C(14)
#define CDISASM_X86_FAMILY_SSE3 UINT16_C(15)
#define CDISASM_X86_FAMILY_SSSE3 UINT16_C(16)
#define CDISASM_X86_FAMILY_SSE4 UINT16_C(17)
#define CDISASM_X86_FAMILY_AVX UINT16_C(18)
#define CDISASM_X86_FAMILY_AVX2 UINT16_C(19)
#define CDISASM_X86_FAMILY_F16C UINT16_C(20)
#define CDISASM_X86_FAMILY_FMA3 UINT16_C(21)
#define CDISASM_X86_FAMILY_XOP UINT16_C(22)
#define CDISASM_X86_FAMILY_FMA4 UINT16_C(23)
#define CDISASM_X86_FAMILY_AES UINT16_C(24)
#define CDISASM_X86_FAMILY_PCLMUL UINT16_C(25)
#define CDISASM_X86_FAMILY_SHA UINT16_C(26)
#define CDISASM_X86_FAMILY_GFNI UINT16_C(27)
#define CDISASM_X86_FAMILY_BITMANIP UINT16_C(28)
#define CDISASM_X86_FAMILY_AVX10 UINT16_C(29)
#define CDISASM_X86_FAMILY_AMX UINT16_C(30)
#define CDISASM_X86_FAMILY_FIRST CDISASM_X86_FAMILY_AVX512_EVEX
#define CDISASM_X86_FAMILY_LAST CDISASM_X86_FAMILY_AMX

/** Bitmask form of the family IDs.  Bit N represents family ID N+1. */
typedef uint64_t cdisasm_x86_family_mask;
#define CDISASM_X86_FAMILY_MASK_NONE UINT64_C(0)
#define CDISASM_X86_FAMILY_MASK_AVX512_EVEX \
    (UINT64_C(1) << (CDISASM_X86_FAMILY_AVX512_EVEX - UINT16_C(1)))
#define CDISASM_X86_FAMILY_MASK_APX_EVEX \
    (UINT64_C(1) << (CDISASM_X86_FAMILY_APX_EVEX - UINT16_C(1)))
#define CDISASM_X86_FAMILY_MASK_AVX2_GATHER \
    (UINT64_C(1) << (CDISASM_X86_FAMILY_AVX2_GATHER - UINT16_C(1)))
#define CDISASM_X86_FAMILY_MASK_FRED \
    (UINT64_C(1) << (CDISASM_X86_FAMILY_FRED - UINT16_C(1)))
#define CDISASM_X86_FAMILY_MASK_TDX \
    (UINT64_C(1) << (CDISASM_X86_FAMILY_TDX - UINT16_C(1)))
#define CDISASM_X86_FAMILY_MASK_VIA_PADLOCK \
    (UINT64_C(1) << (CDISASM_X86_FAMILY_VIA_PADLOCK - UINT16_C(1)))
#define CDISASM_X86_FAMILY_MASK_X87 \
    (UINT64_C(1) << (CDISASM_X86_FAMILY_X87 - UINT16_C(1)))
#define CDISASM_X86_FAMILY_MASK_MOVRS \
    (UINT64_C(1) << (CDISASM_X86_FAMILY_MOVRS - UINT16_C(1)))
#define CDISASM_X86_FAMILY_MASK_INTEL_VMX \
    (UINT64_C(1) << (CDISASM_X86_FAMILY_INTEL_VMX - UINT16_C(1)))
#define CDISASM_X86_FAMILY_MASK_AMD_SVM \
    (UINT64_C(1) << (CDISASM_X86_FAMILY_AMD_SVM - UINT16_C(1)))
#define CDISASM_X86_FAMILY_MASK_MMX \
    (UINT64_C(1) << (CDISASM_X86_FAMILY_MMX - UINT16_C(1)))
#define CDISASM_X86_FAMILY_MASK_3DNOW \
    (UINT64_C(1) << (CDISASM_X86_FAMILY_3DNOW - UINT16_C(1)))
#define CDISASM_X86_FAMILY_MASK_SSE \
    (UINT64_C(1) << (CDISASM_X86_FAMILY_SSE - UINT16_C(1)))
#define CDISASM_X86_FAMILY_MASK_SSE2 \
    (UINT64_C(1) << (CDISASM_X86_FAMILY_SSE2 - UINT16_C(1)))
#define CDISASM_X86_FAMILY_MASK_SSE3 \
    (UINT64_C(1) << (CDISASM_X86_FAMILY_SSE3 - UINT16_C(1)))
#define CDISASM_X86_FAMILY_MASK_SSSE3 \
    (UINT64_C(1) << (CDISASM_X86_FAMILY_SSSE3 - UINT16_C(1)))
#define CDISASM_X86_FAMILY_MASK_SSE4 \
    (UINT64_C(1) << (CDISASM_X86_FAMILY_SSE4 - UINT16_C(1)))
#define CDISASM_X86_FAMILY_MASK_AVX \
    (UINT64_C(1) << (CDISASM_X86_FAMILY_AVX - UINT16_C(1)))
#define CDISASM_X86_FAMILY_MASK_AVX2 \
    (UINT64_C(1) << (CDISASM_X86_FAMILY_AVX2 - UINT16_C(1)))
#define CDISASM_X86_FAMILY_MASK_F16C \
    (UINT64_C(1) << (CDISASM_X86_FAMILY_F16C - UINT16_C(1)))
#define CDISASM_X86_FAMILY_MASK_FMA3 \
    (UINT64_C(1) << (CDISASM_X86_FAMILY_FMA3 - UINT16_C(1)))
#define CDISASM_X86_FAMILY_MASK_XOP \
    (UINT64_C(1) << (CDISASM_X86_FAMILY_XOP - UINT16_C(1)))
#define CDISASM_X86_FAMILY_MASK_FMA4 \
    (UINT64_C(1) << (CDISASM_X86_FAMILY_FMA4 - UINT16_C(1)))
#define CDISASM_X86_FAMILY_MASK_AES \
    (UINT64_C(1) << (CDISASM_X86_FAMILY_AES - UINT16_C(1)))
#define CDISASM_X86_FAMILY_MASK_PCLMUL \
    (UINT64_C(1) << (CDISASM_X86_FAMILY_PCLMUL - UINT16_C(1)))
#define CDISASM_X86_FAMILY_MASK_SHA \
    (UINT64_C(1) << (CDISASM_X86_FAMILY_SHA - UINT16_C(1)))
#define CDISASM_X86_FAMILY_MASK_GFNI \
    (UINT64_C(1) << (CDISASM_X86_FAMILY_GFNI - UINT16_C(1)))
#define CDISASM_X86_FAMILY_MASK_BITMANIP \
    (UINT64_C(1) << (CDISASM_X86_FAMILY_BITMANIP - UINT16_C(1)))
#define CDISASM_X86_FAMILY_MASK_AVX10 \
    (UINT64_C(1) << (CDISASM_X86_FAMILY_AVX10 - UINT16_C(1)))
#define CDISASM_X86_FAMILY_MASK_AMX \
    (UINT64_C(1) << (CDISASM_X86_FAMILY_AMX - UINT16_C(1)))
#define CDISASM_X86_FAMILY_MASK_ALL \
    (CDISASM_X86_FAMILY_MASK_AVX512_EVEX \
        | CDISASM_X86_FAMILY_MASK_APX_EVEX \
        | CDISASM_X86_FAMILY_MASK_AVX2_GATHER \
        | CDISASM_X86_FAMILY_MASK_FRED \
        | CDISASM_X86_FAMILY_MASK_TDX \
        | CDISASM_X86_FAMILY_MASK_VIA_PADLOCK \
        | CDISASM_X86_FAMILY_MASK_X87 \
        | CDISASM_X86_FAMILY_MASK_MOVRS \
        | CDISASM_X86_FAMILY_MASK_INTEL_VMX \
        | CDISASM_X86_FAMILY_MASK_AMD_SVM \
        | CDISASM_X86_FAMILY_MASK_MMX \
        | CDISASM_X86_FAMILY_MASK_3DNOW \
        | CDISASM_X86_FAMILY_MASK_SSE \
        | CDISASM_X86_FAMILY_MASK_SSE2 \
        | CDISASM_X86_FAMILY_MASK_SSE3 \
        | CDISASM_X86_FAMILY_MASK_SSSE3 \
        | CDISASM_X86_FAMILY_MASK_SSE4 \
        | CDISASM_X86_FAMILY_MASK_AVX \
        | CDISASM_X86_FAMILY_MASK_AVX2 \
        | CDISASM_X86_FAMILY_MASK_F16C \
        | CDISASM_X86_FAMILY_MASK_FMA3 \
        | CDISASM_X86_FAMILY_MASK_XOP \
        | CDISASM_X86_FAMILY_MASK_FMA4 \
        | CDISASM_X86_FAMILY_MASK_AES \
        | CDISASM_X86_FAMILY_MASK_PCLMUL \
        | CDISASM_X86_FAMILY_MASK_SHA \
        | CDISASM_X86_FAMILY_MASK_GFNI \
        | CDISASM_X86_FAMILY_MASK_BITMANIP \
        | CDISASM_X86_FAMILY_MASK_AVX10 \
        | CDISASM_X86_FAMILY_MASK_AMX)
/**
 * Default family selection for normal decoding.  It keeps architecture-wide,
 * unprivileged families enabled and leaves Intel privileged (FRED/TDX/VMX),
 * AMD SVM, and VIA-specific PadLock forms opt-in through family_value.
 */
#define CDISASM_X86_FAMILY_MASK_PRIVILEGED_OR_VENDOR \
    (CDISASM_X86_FAMILY_MASK_FRED \
        | CDISASM_X86_FAMILY_MASK_TDX \
        | CDISASM_X86_FAMILY_MASK_VIA_PADLOCK \
        | CDISASM_X86_FAMILY_MASK_INTEL_VMX \
        | CDISASM_X86_FAMILY_MASK_AMD_SVM)
#define CDISASM_X86_FAMILY_MASK_NON_DEFAULT \
    (CDISASM_X86_FAMILY_MASK_3DNOW \
        | CDISASM_X86_FAMILY_MASK_XOP \
        | CDISASM_X86_FAMILY_MASK_FMA4)
#define CDISASM_X86_FAMILY_MASK_DEFAULT \
    (CDISASM_X86_FAMILY_MASK_ALL \
        & ~(CDISASM_X86_FAMILY_MASK_PRIVILEGED_OR_VENDOR \
            | CDISASM_X86_FAMILY_MASK_NON_DEFAULT))

typedef uint16_t cdisasm_x86_operand_rule_id;
#define CDISASM_X86_OPERAND_RULE_NONE UINT16_C(0)
#define CDISASM_X86_OPERAND_RULE_EVEX_VECTOR_MASK UINT16_C(1)
#define CDISASM_X86_OPERAND_RULE_APX_N3 UINT16_C(2)
#define CDISASM_X86_OPERAND_RULE_VSIB_GATHER UINT16_C(3)
#define CDISASM_X86_OPERAND_RULE_ZERO_OPERANDS UINT16_C(4)
#define CDISASM_X86_OPERAND_RULE_X87_STACK UINT16_C(5)

typedef uint16_t cdisasm_x86_legality_rule_id;
#define CDISASM_X86_LEGALITY_RULE_NONE UINT16_C(0)
#define CDISASM_X86_LEGALITY_RULE_AVX512_EVEX UINT16_C(1)
#define CDISASM_X86_LEGALITY_RULE_APX_F_N3 UINT16_C(2)
#define CDISASM_X86_LEGALITY_RULE_AVX2_VSIB UINT16_C(3)
#define CDISASM_X86_LEGALITY_RULE_FRED UINT16_C(4)
#define CDISASM_X86_LEGALITY_RULE_TDX UINT16_C(5)
#define CDISASM_X86_LEGALITY_RULE_VIA_PADLOCK UINT16_C(6)
#define CDISASM_X86_LEGALITY_RULE_X87 UINT16_C(7)
#define CDISASM_X86_LEGALITY_RULE_MOVRS UINT16_C(8)
#define CDISASM_X86_LEGALITY_RULE_INTEL_VMX UINT16_C(9)
#define CDISASM_X86_LEGALITY_RULE_AMD_SVM UINT16_C(10)

#define CDISASM_X86_PRIVILEGE_ANY UINT8_C(0)
#define CDISASM_X86_PRIVILEGE_RING0 UINT8_C(1)
#define CDISASM_X86_PRIVILEGE_VMX_ROOT UINT8_C(2)
#define CDISASM_X86_PRIVILEGE_SVM_HOST UINT8_C(3)

#define CDISASM_X86_VENDOR_ANY UINT8_C(0)
#define CDISASM_X86_VENDOR_INTEL UINT8_C(1)
#define CDISASM_X86_VENDOR_AMD UINT8_C(2)
#define CDISASM_X86_VENDOR_VIA UINT8_C(3)

/** Shared metadata for one direct or validation x86 opcode family. */
typedef struct cdisasm_x86_family_descriptor {
    cdisasm_x86_family_id family_id;
    /** Coarse bitmap-0 runtime requirement; exact ISA_SET bits are checked
     * by the selected legality rule against cdisasm_x86_decode_flags. */
    uint64_t required_flags;
    cdisasm_x86_mode_mask allowed_modes;
    cdisasm_x86_operand_rule_id operand_rule;
    cdisasm_x86_legality_rule_id legality_rule;
    uint8_t privilege_level;
    uint8_t vendor;
} cdisasm_x86_family_descriptor;

/**
 * Stable x86 CPU profiles for cdisasm_decode.
 *
 * The upper 16 bits contain CDISASM_CPU_GROUP_X86. Architecture-local
 * ordinals 0x0001 through 0x0026 form the original chronological, append-only
 * ISA list. Later exact-processor and CPU-plus-coprocessor profiles are
 * appended without renumbering those ordinals. Relational comparisons for
 * mode cutoffs are meaningful only when both IDs are in the chronological
 * 0x0001..0x0026 range; appended profiles use explicit per-profile metadata.
 * Instruction availability uses the selected Intel/AMD profile because
 * neither later IDs nor vendor branches are feature supersets.
 * CDISASM_CPU_X86 uses ordinal zero as the compatibility profile and bypasses
 * CPU-capability filtering; the decode flags still independently select which
 * opcode families are allowed. It must not be used in ordered comparisons.
 */
typedef cdisasm_cpu_id cdisasm_x86_cpu_id;
#define CDISASM_CPU_X86 \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0000))
#define CDISASM_CPU_GENERIC CDISASM_CPU_X86
#define CDISASM_CPU_8086 \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0001))
#define CDISASM_CPU_8088 CDISASM_CPU_8086
#define CDISASM_CPU_8086_8088 CDISASM_CPU_8086
#define CDISASM_CPU_80186 \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0002))
#define CDISASM_CPU_80286 \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0003))
#define CDISASM_CPU_80386 \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0004))
#define CDISASM_CPU_386 CDISASM_CPU_80386
#define CDISASM_CPU_80486 \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0005))
#define CDISASM_CPU_486 CDISASM_CPU_80486
#define CDISASM_CPU_80486_CPUID \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0006))
#define CDISASM_CPU_LATE_80486 CDISASM_CPU_80486_CPUID
#define CDISASM_CPU_486_CPUID CDISASM_CPU_80486_CPUID
#define CDISASM_CPU_PENTIUM \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0007))
#define CDISASM_CPU_PENTIUM_PRO \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0008))
#define CDISASM_CPU_PENTIUM_MMX \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0009))
#define CDISASM_CPU_PENTIUM_II \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x000a))
#define CDISASM_CPU_AMD_K6_2 \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x000b))
#define CDISASM_CPU_K6_2 CDISASM_CPU_AMD_K6_2
#define CDISASM_CPU_PENTIUM_III \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x000c))
#define CDISASM_CPU_PENTIUM_4 \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x000d))
#define CDISASM_CPU_ATHLON_64 \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x000e))
#define CDISASM_CPU_AMD_ATHLON_64 CDISASM_CPU_ATHLON_64
#define CDISASM_CPU_AMD_OPTERON CDISASM_CPU_ATHLON_64
#define CDISASM_CPU_OPTERON CDISASM_CPU_ATHLON_64
#define CDISASM_CPU_PRESCOTT \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x000f))
#define CDISASM_CPU_INTEL_VT_X \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0010))
#define CDISASM_CPU_AMD_V \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0011))
#define CDISASM_CPU_CORE_2 \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0012))
#define CDISASM_CPU_PENRYN \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0013))
#define CDISASM_CPU_AMD_BARCELONA \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0014))
#define CDISASM_CPU_BARCELONA CDISASM_CPU_AMD_BARCELONA
#define CDISASM_CPU_NEHALEM \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0015))
#define CDISASM_CPU_WESTMERE \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0016))
#define CDISASM_CPU_SANDY_BRIDGE \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0017))
#define CDISASM_CPU_AMD_BULLDOZER \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0018))
#define CDISASM_CPU_BULLDOZER CDISASM_CPU_AMD_BULLDOZER
#define CDISASM_CPU_IVY_BRIDGE \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0019))
#define CDISASM_CPU_HASWELL \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x001a))
#define CDISASM_CPU_BROADWELL \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x001b))
#define CDISASM_CPU_SKYLAKE \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x001c))
#define CDISASM_CPU_GOLDMONT \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x001d))
#define CDISASM_CPU_AMD_ZEN \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x001e))
#define CDISASM_CPU_ZEN CDISASM_CPU_AMD_ZEN
#define CDISASM_CPU_SKYLAKE_SP \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x001f))
#define CDISASM_CPU_INTEL_SKYLAKE_SP CDISASM_CPU_SKYLAKE_SP
#define CDISASM_CPU_ICE_LAKE \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0020))
#define CDISASM_CPU_TIGER_LAKE \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0021))
#define CDISASM_CPU_ALDER_LAKE \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0022))
#define CDISASM_CPU_AMD_ZEN_4 \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0023))
#define CDISASM_CPU_ZEN_4 CDISASM_CPU_AMD_ZEN_4
#define CDISASM_CPU_SAPPHIRE_RAPIDS \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0024))
#define CDISASM_CPU_AVX10 \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0025))
#define CDISASM_CPU_APX \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0026))
/* Modern Intel SKUs whose product feature set deliberately omits AVX. */
#define CDISASM_CPU_CELERON_G1840 \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0027))
#define CDISASM_CPU_INTEL_CELERON_G1840 CDISASM_CPU_CELERON_G1840
#define CDISASM_CPU_HASWELL_CELERON CDISASM_CPU_CELERON_G1840
#define CDISASM_CPU_CELERON_G3900 \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0028))
#define CDISASM_CPU_INTEL_CELERON_G3900 CDISASM_CPU_CELERON_G3900
#define CDISASM_CPU_SKYLAKE_CELERON CDISASM_CPU_CELERON_G3900
#define CDISASM_CPU_CELERON_N3350 \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0029))
#define CDISASM_CPU_INTEL_CELERON_N3350 CDISASM_CPU_CELERON_N3350
#define CDISASM_CPU_APOLLO_LAKE_CELERON CDISASM_CPU_CELERON_N3350
#define CDISASM_CPU_CELERON_N4020 \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x002a))
#define CDISASM_CPU_INTEL_CELERON_N4020 CDISASM_CPU_CELERON_N4020
#define CDISASM_CPU_CELERON_J4125 CDISASM_CPU_CELERON_N4020
#define CDISASM_CPU_GEMINI_LAKE_REFRESH_CELERON CDISASM_CPU_CELERON_N4020
#define CDISASM_CPU_CELERON_G5900 \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x002b))
#define CDISASM_CPU_INTEL_CELERON_G5900 CDISASM_CPU_CELERON_G5900
#define CDISASM_CPU_CELERON_G5905 CDISASM_CPU_CELERON_G5900
#define CDISASM_CPU_COMET_LAKE_CELERON CDISASM_CPU_CELERON_G5900
#define CDISASM_CPU_PENTIUM_SILVER_N6000 \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x002c))
#define CDISASM_CPU_INTEL_PENTIUM_SILVER_N6000 \
    CDISASM_CPU_PENTIUM_SILVER_N6000
#define CDISASM_CPU_CELERON_N5105 CDISASM_CPU_PENTIUM_SILVER_N6000
#define CDISASM_CPU_JASPER_LAKE_NO_AVX CDISASM_CPU_PENTIUM_SILVER_N6000
/* Optional external x87 coprocessor combinations for pre-80486 CPUs. */
#define CDISASM_CPU_8086_8087 \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x002d))
#define CDISASM_CPU_8088_8087 CDISASM_CPU_8086_8087
#define CDISASM_CPU_80186_80187 \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x002e))
#define CDISASM_CPU_80286_80287 \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x002f))
#define CDISASM_CPU_286_287 CDISASM_CPU_80286_80287
#define CDISASM_CPU_80386_80387 \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0030))
#define CDISASM_CPU_386_387 CDISASM_CPU_80386_80387
#define CDISASM_CPU_GRANITE_RAPIDS \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0031))
#define CDISASM_CPU_ARROW_LAKE \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0032))
#define CDISASM_CPU_INTEL_ARROW_LAKE CDISASM_CPU_ARROW_LAKE
#define CDISASM_CPU_CORE_ULTRA_200 CDISASM_CPU_ARROW_LAKE
#define CDISASM_CPU_DIAMOND_RAPIDS \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0033))
#define CDISASM_CPU_INTEL_DIAMOND_RAPIDS CDISASM_CPU_DIAMOND_RAPIDS
#define CDISASM_CPU_DMR CDISASM_CPU_DIAMOND_RAPIDS
#define CDISASM_CPU_KNIGHTS_MILL \
    (CDISASM_CPU_GROUP_X86 | UINT32_C(0x0034))
#define CDISASM_CPU_INTEL_KNIGHTS_MILL CDISASM_CPU_KNIGHTS_MILL
#define CDISASM_CPU_KNM CDISASM_CPU_KNIGHTS_MILL
#define CDISASM_CPU_FIRST CDISASM_CPU_8086
/** Latest chronological ISA-level profile, not the greatest numeric ID. */
#define CDISASM_CPU_LATEST CDISASM_CPU_DIAMOND_RAPIDS
/** Greatest valid named CPU-profile value; use this for range validation. */
#define CDISASM_CPU_LAST CDISASM_CPU_KNIGHTS_MILL

/**
 * Runtime x86 opcode-family bitmap set.
 *
 * A NULL or all-zero set admits only scalar/base opcodes. Bitmap 0 bits 0..63
 * currently select FPU, MMX,
 * 3DNow!, SSE, SSE2, SSE3, SSSE3, SSE4, AVX, AVX2, F16C, FMA3, XOP, FMA4,
 * AES, PCLMUL, SHA, GFNI, bit manipulation, AVX-512, AVX10, AMX, APX,
 * SMX, system, CET, state, transactional, security, memory-hint, and
 * undocumented families, SM3, SM4, granular implemented AVX-512 families,
 * COMPRESS/EXPAND, VAES, VPCLMULQDQ, SHA-512, AMX subfamilies, VMX/SVM,
 * SSE4 variants, BMI1/BMI2, AVX-512 CD, AVX-VNNI, AVX-VNNI-INT8, and
 * AVX-VNNI-INT16. Nonzero
 * masks are accepted only by a USE_EXTRA_OPCODES build and remain subject to
 * the CPU profile. The historical AVX512, AES, PCLMUL, SHA, AMX, SSE4, and
 * BITMANIP bits remain backward-compatible umbrellas for their appended,
 * more-specific selectors. Intel VMX and AMD SVM are deliberately independent
 * families. Bits 64 through CDISASM_X86_DECODE_BIT_LAST are append-only,
 * exact selectors for pinned XED ISA_SET identities that had no exact legacy
 * selector. ARM uses the same storage size but an independent namespace.
 */
typedef cdisasm_decode_flags cdisasm_x86_decode_flags;
/* Legacy scalar spelling retained as the type of one bitmap word. */
typedef cdisasm_decode_flag_bitmap cdisasm_x86_decode_option;
#define CDISASM_X86_DECODE_FLAGS_FAMILY_BITMAP 0u

/**
 * CPU-bound x86 decode context.  The CPU ID is retained because a small
 * number of architectural rules are profile-specific even when their feature
 * bitmap is identical; mode is copied explicitly so a later decode call does
 * not need a separate mode argument.  flags is the complete CPU/mode
 * capability set, family_mask is its special-family projection, and
 * family_value is the ordinary default selection for callers that want to
 * avoid privileged or vendor-specific families.
 */
typedef struct cdisasm_x86_decode_context {
    cdisasm_x86_cpu_id cpu_id;
    cdisasm_x86_mode mode;
    cdisasm_x86_decode_flags flags;
    /** All special families available for this CPU and mode. */
    cdisasm_x86_family_mask family_mask;
    /** Default special-family selection; always a subset of family_mask. */
    cdisasm_x86_family_mask family_value;
} cdisasm_x86_decode_context;

/**
 * Adds one available family to context->family_value.
 * Returns nonzero on success; invalid or unavailable families return zero.
 */
CDISASM_X86_API int CDISASM_CALL
cdisasm_x86_decode_context_add_family(
    cdisasm_x86_decode_context *context,
    cdisasm_x86_family_id family_id);

/**
 * Removes one available family from context->family_value.
 * Returns nonzero on success; invalid or unavailable families return zero.
 */
CDISASM_X86_API int CDISASM_CALL
cdisasm_x86_decode_context_remove_family(
    cdisasm_x86_decode_context *context,
    cdisasm_x86_family_id family_id);

/** Returns all special families available in the context's CPU/mode. */
CDISASM_X86_API cdisasm_x86_family_mask CDISASM_CALL
cdisasm_x86_decode_context_get_available_families(
    const cdisasm_x86_decode_context *context);

/** Returns the currently selected special families in the context. */
CDISASM_X86_API cdisasm_x86_family_mask CDISASM_CALL
cdisasm_x86_decode_context_get_set_families(
    const cdisasm_x86_decode_context *context);

/** Append-only logical x86 bit IDs for cdisasm_decode_flags_*_bit helpers. */
typedef uint32_t cdisasm_x86_decode_bit_id;
/** Sentinel used by generated metadata for scalar/core ISA sets. */
#define CDISASM_X86_DECODE_BIT_NONE UINT32_MAX
#define CDISASM_X86_DECODE_BIT_FPU UINT32_C(0)
#define CDISASM_X86_DECODE_BIT_MMX UINT32_C(1)
#define CDISASM_X86_DECODE_BIT_3DNOW UINT32_C(2)
#define CDISASM_X86_DECODE_BIT_SSE UINT32_C(3)
#define CDISASM_X86_DECODE_BIT_SSE2 UINT32_C(4)
#define CDISASM_X86_DECODE_BIT_SSE3 UINT32_C(5)
#define CDISASM_X86_DECODE_BIT_SSSE3 UINT32_C(6)
#define CDISASM_X86_DECODE_BIT_SSE4 UINT32_C(7)
#define CDISASM_X86_DECODE_BIT_AVX UINT32_C(8)
#define CDISASM_X86_DECODE_BIT_AVX2 UINT32_C(9)
#define CDISASM_X86_DECODE_BIT_F16C UINT32_C(10)
#define CDISASM_X86_DECODE_BIT_FMA3 UINT32_C(11)
#define CDISASM_X86_DECODE_BIT_XOP UINT32_C(12)
#define CDISASM_X86_DECODE_BIT_FMA4 UINT32_C(13)
#define CDISASM_X86_DECODE_BIT_AES UINT32_C(14)
#define CDISASM_X86_DECODE_BIT_PCLMUL UINT32_C(15)
#define CDISASM_X86_DECODE_BIT_SHA UINT32_C(16)
#define CDISASM_X86_DECODE_BIT_GFNI UINT32_C(17)
#define CDISASM_X86_DECODE_BIT_BITMANIP UINT32_C(18)
#define CDISASM_X86_DECODE_BIT_AVX512 UINT32_C(19)
#define CDISASM_X86_DECODE_BIT_AVX10 UINT32_C(20)
#define CDISASM_X86_DECODE_BIT_AMX UINT32_C(21)
#define CDISASM_X86_DECODE_BIT_APX UINT32_C(22)
#define CDISASM_X86_DECODE_BIT_SMX UINT32_C(23)
#define CDISASM_X86_DECODE_BIT_VIRTUALIZATION CDISASM_X86_DECODE_BIT_SMX
#define CDISASM_X86_DECODE_BIT_SYSTEM UINT32_C(24)
#define CDISASM_X86_DECODE_BIT_CET UINT32_C(25)
#define CDISASM_X86_DECODE_BIT_STATE UINT32_C(26)
#define CDISASM_X86_DECODE_BIT_TRANSACTIONAL UINT32_C(27)
#define CDISASM_X86_DECODE_BIT_SECURITY UINT32_C(28)
#define CDISASM_X86_DECODE_BIT_MEMORY_HINTS UINT32_C(29)
#define CDISASM_X86_DECODE_BIT_UNDOCUMENTED UINT32_C(30)
#define CDISASM_X86_DECODE_BIT_SM3 UINT32_C(31)
#define CDISASM_X86_DECODE_BIT_SM4 UINT32_C(32)
#define CDISASM_X86_DECODE_BIT_AVX512_VBMI2 UINT32_C(33)
#define CDISASM_X86_DECODE_BIT_AVX512_VPOPCNTDQ UINT32_C(34)
#define CDISASM_X86_DECODE_BIT_AVX512_BITALG UINT32_C(35)
#define CDISASM_X86_DECODE_BIT_COMPRESS_EXPAND UINT32_C(36)
#define CDISASM_X86_DECODE_BIT_AVX512_IFMA UINT32_C(37)
#define CDISASM_X86_DECODE_BIT_AVX512_VBMI UINT32_C(38)
#define CDISASM_X86_DECODE_BIT_AVX512_VNNI UINT32_C(39)
#define CDISASM_X86_DECODE_BIT_VAES UINT32_C(40)
#define CDISASM_X86_DECODE_BIT_VPCLMULQDQ UINT32_C(41)
#define CDISASM_X86_DECODE_BIT_SHA512 UINT32_C(42)
#define CDISASM_X86_DECODE_BIT_AMX_TILE UINT32_C(43)
#define CDISASM_X86_DECODE_BIT_AMX_INT8 UINT32_C(44)
#define CDISASM_X86_DECODE_BIT_AMX_BF16 UINT32_C(45)
#define CDISASM_X86_DECODE_BIT_AMX_FP16 UINT32_C(46)
#define CDISASM_X86_DECODE_BIT_AMX_COMPLEX UINT32_C(47)
#define CDISASM_X86_DECODE_BIT_AMX_FP8 UINT32_C(48)
#define CDISASM_X86_DECODE_BIT_AMX_MOVRS UINT32_C(49)
#define CDISASM_X86_DECODE_BIT_AMX_AVX512 UINT32_C(50)
#define CDISASM_X86_DECODE_BIT_AVX512_DQ UINT32_C(51)
#define CDISASM_X86_DECODE_BIT_AVX512_BW UINT32_C(52)
#define CDISASM_X86_DECODE_BIT_VMX UINT32_C(53)
#define CDISASM_X86_DECODE_BIT_SVM UINT32_C(54)
#define CDISASM_X86_DECODE_BIT_INTEL_VIRTUALIZATION \
    CDISASM_X86_DECODE_BIT_VMX
#define CDISASM_X86_DECODE_BIT_AMD_VIRTUALIZATION \
    CDISASM_X86_DECODE_BIT_SVM
#define CDISASM_X86_DECODE_BIT_SSE41 UINT32_C(55)
#define CDISASM_X86_DECODE_BIT_SSE42 UINT32_C(56)
#define CDISASM_X86_DECODE_BIT_SSE4A UINT32_C(57)
#define CDISASM_X86_DECODE_BIT_BMI1 UINT32_C(58)
#define CDISASM_X86_DECODE_BIT_BMI2 UINT32_C(59)
#define CDISASM_X86_DECODE_BIT_AVX512_CD UINT32_C(60)
#define CDISASM_X86_DECODE_BIT_AVX_VNNI UINT32_C(61)
#define CDISASM_X86_DECODE_BIT_AVX_VNNI_INT8 UINT32_C(62)
#define CDISASM_X86_DECODE_BIT_AVX_VNNI_INT16 UINT32_C(63)

/* Exact pinned-XED ISA_SET selectors append after the original bitmap word. */
#include "cdisasm_x86_isa_set_bits.inc"

/* Existing mask spellings below address bitmap 0. They remain useful for
 * OR-composed initializers; logical bit IDs above extend naturally past 63. */
#define CDISASM_X86_DECODE_FLAG_BASE UINT64_C(0x00000000)
#define CDISASM_X86_DECODE_FLAG_FPU UINT64_C(0x00000001)
#define CDISASM_X86_DECODE_FLAG_MMX UINT64_C(0x00000002)
#define CDISASM_X86_DECODE_FLAG_3DNOW UINT64_C(0x00000004)
#define CDISASM_X86_DECODE_FLAG_SSE UINT64_C(0x00000008)
#define CDISASM_X86_DECODE_FLAG_SSE2 UINT64_C(0x00000010)
#define CDISASM_X86_DECODE_FLAG_SSE3 UINT64_C(0x00000020)
#define CDISASM_X86_DECODE_FLAG_SSSE3 UINT64_C(0x00000040)
#define CDISASM_X86_DECODE_FLAG_SSE4 UINT64_C(0x00000080)
#define CDISASM_X86_DECODE_FLAG_AVX UINT64_C(0x00000100)
#define CDISASM_X86_DECODE_FLAG_AVX2 UINT64_C(0x00000200)
#define CDISASM_X86_DECODE_FLAG_F16C UINT64_C(0x00000400)
#define CDISASM_X86_DECODE_FLAG_FMA3 UINT64_C(0x00000800)
#define CDISASM_X86_DECODE_FLAG_XOP UINT64_C(0x00001000)
#define CDISASM_X86_DECODE_FLAG_FMA4 UINT64_C(0x00002000)
#define CDISASM_X86_DECODE_FLAG_AES UINT64_C(0x00004000)
#define CDISASM_X86_DECODE_FLAG_PCLMUL UINT64_C(0x00008000)
#define CDISASM_X86_DECODE_FLAG_SHA UINT64_C(0x00010000)
#define CDISASM_X86_DECODE_FLAG_GFNI UINT64_C(0x00020000)
#define CDISASM_X86_DECODE_FLAG_BITMANIP UINT64_C(0x00040000)
#define CDISASM_X86_DECODE_FLAG_AVX512 UINT64_C(0x00080000)
#define CDISASM_X86_DECODE_FLAG_AVX10 UINT64_C(0x00100000)
#define CDISASM_X86_DECODE_FLAG_AMX UINT64_C(0x00200000)
#define CDISASM_X86_DECODE_FLAG_APX UINT64_C(0x00400000)
#define CDISASM_X86_DECODE_FLAG_SMX UINT64_C(0x00800000)
/* Historical source spelling. Since 11.27 it selects SMX only; use the
 * vendor-specific VMX or SVM flag for hardware virtualization instructions. */
#define CDISASM_X86_DECODE_FLAG_VIRTUALIZATION \
    CDISASM_X86_DECODE_FLAG_SMX
#define CDISASM_X86_DECODE_FLAG_SYSTEM UINT64_C(0x01000000)
#define CDISASM_X86_DECODE_FLAG_CET UINT64_C(0x02000000)
#define CDISASM_X86_DECODE_FLAG_STATE UINT64_C(0x04000000)
#define CDISASM_X86_DECODE_FLAG_TRANSACTIONAL UINT64_C(0x08000000)
#define CDISASM_X86_DECODE_FLAG_SECURITY UINT64_C(0x10000000)
#define CDISASM_X86_DECODE_FLAG_MEMORY_HINTS UINT64_C(0x20000000)
#define CDISASM_X86_DECODE_FLAG_UNDOCUMENTED UINT64_C(0x40000000)
#define CDISASM_X86_DECODE_FLAG_SM3 UINT64_C(0x080000000)
#define CDISASM_X86_DECODE_FLAG_SM4 UINT64_C(0x100000000)
#define CDISASM_X86_DECODE_FLAG_AVX512_VBMI2 UINT64_C(0x200000000)
#define CDISASM_X86_DECODE_FLAG_AVX512_VPOPCNTDQ UINT64_C(0x400000000)
#define CDISASM_X86_DECODE_FLAG_AVX512_BITALG UINT64_C(0x800000000)
#define CDISASM_X86_DECODE_FLAG_COMPRESS_EXPAND UINT64_C(0x1000000000)
#define CDISASM_X86_DECODE_FLAG_AVX512_IFMA UINT64_C(0x2000000000)
#define CDISASM_X86_DECODE_FLAG_AVX512_VBMI UINT64_C(0x4000000000)
#define CDISASM_X86_DECODE_FLAG_AVX512_VNNI UINT64_C(0x8000000000)
#define CDISASM_X86_DECODE_FLAG_VAES UINT64_C(0x10000000000)
#define CDISASM_X86_DECODE_FLAG_VPCLMULQDQ UINT64_C(0x20000000000)
#define CDISASM_X86_DECODE_FLAG_SHA512 UINT64_C(0x40000000000)
#define CDISASM_X86_DECODE_FLAG_AMX_TILE UINT64_C(0x80000000000)
#define CDISASM_X86_DECODE_FLAG_AMX_INT8 UINT64_C(0x100000000000)
#define CDISASM_X86_DECODE_FLAG_AMX_BF16 UINT64_C(0x200000000000)
#define CDISASM_X86_DECODE_FLAG_AMX_FP16 UINT64_C(0x400000000000)
#define CDISASM_X86_DECODE_FLAG_AMX_COMPLEX UINT64_C(0x800000000000)
#define CDISASM_X86_DECODE_FLAG_AMX_FP8 UINT64_C(0x1000000000000)
#define CDISASM_X86_DECODE_FLAG_AMX_MOVRS UINT64_C(0x2000000000000)
#define CDISASM_X86_DECODE_FLAG_AMX_AVX512 UINT64_C(0x4000000000000)
#define CDISASM_X86_DECODE_FLAG_AVX512_DQ UINT64_C(0x8000000000000)
#define CDISASM_X86_DECODE_FLAG_AVX512_BW UINT64_C(0x10000000000000)
#define CDISASM_X86_DECODE_FLAG_VMX UINT64_C(0x20000000000000)
#define CDISASM_X86_DECODE_FLAG_SVM UINT64_C(0x40000000000000)
/* Readable vendor-specific aliases; these do not allocate additional bits. */
#define CDISASM_X86_DECODE_FLAG_INTEL_VIRTUALIZATION \
    CDISASM_X86_DECODE_FLAG_VMX
#define CDISASM_X86_DECODE_FLAG_AMD_VIRTUALIZATION \
    CDISASM_X86_DECODE_FLAG_SVM
#define CDISASM_X86_DECODE_FLAG_SSE41 UINT64_C(0x80000000000000)
#define CDISASM_X86_DECODE_FLAG_SSE42 UINT64_C(0x100000000000000)
#define CDISASM_X86_DECODE_FLAG_SSE4A UINT64_C(0x200000000000000)
#define CDISASM_X86_DECODE_FLAG_BMI1 UINT64_C(0x400000000000000)
#define CDISASM_X86_DECODE_FLAG_BMI2 UINT64_C(0x800000000000000)
#define CDISASM_X86_DECODE_FLAG_AVX512_CD UINT64_C(0x1000000000000000)
#define CDISASM_X86_DECODE_FLAG_AVX_VNNI UINT64_C(0x2000000000000000)
#define CDISASM_X86_DECODE_FLAG_AVX_VNNI_INT8 UINT64_C(0x4000000000000000)
#define CDISASM_X86_DECODE_FLAG_AVX_VNNI_INT16 UINT64_C(0x8000000000000000)
#define CDISASM_X86_DECODE_FLAG_ALL UINT64_C(0xffffffffffffffff)
#define CDISASM_X86_DECODE_FLAG_KNOWN_MASK CDISASM_X86_DECODE_FLAG_ALL
#define CDISASM_X86_DECODE_FLAG_KNOWN_MASK_0 \
    CDISASM_X86_DECODE_FLAG_KNOWN_MASK

#define CDISASM_X86_DECODE_FLAGS_INITIALIZER(bitmap0_) \
    CDISASM_DECODE_FLAGS_INITIALIZER(bitmap0_)
#define CDISASM_X86_DECODE_FLAGS_NONE_INITIALIZER \
    CDISASM_X86_DECODE_FLAGS_INITIALIZER(UINT64_C(0))
#define CDISASM_X86_DECODE_FLAGS_ALL_INITIALIZER \
    {{ \
        CDISASM_X86_DECODE_FLAG_KNOWN_MASK_0, \
        CDISASM_X86_DECODE_FLAG_KNOWN_MASK_1, \
        CDISASM_X86_DECODE_FLAG_KNOWN_MASK_2, \
        CDISASM_X86_DECODE_FLAG_KNOWN_MASK_3, \
        CDISASM_X86_DECODE_FLAG_KNOWN_MASK_4, \
        CDISASM_X86_DECODE_FLAG_KNOWN_MASK_5, \
        CDISASM_X86_DECODE_FLAG_KNOWN_MASK_6, \
        CDISASM_X86_DECODE_FLAG_KNOWN_MASK_7 \
    }}

/* Legacy bitmap-0 spellings. Use the plural FLAGS_* initializers for the
 * complete fixed-size set; zero still selects only scalar/base opcodes. */
#define CDISASM_X86_DECODE_OPTION_NONE CDISASM_DECODE_OPTION_NONE
#define CDISASM_X86_DECODE_OPTION_BASE CDISASM_X86_DECODE_FLAG_BASE
#define CDISASM_X86_DECODE_OPTION_ALL CDISASM_X86_DECODE_FLAG_ALL

/* Readable aliases for applications that prefer USE_* flag names. */
#define CDISASM_X86_DECODE_USE_FPU CDISASM_X86_DECODE_FLAG_FPU
#define CDISASM_X86_DECODE_USE_MMX CDISASM_X86_DECODE_FLAG_MMX
#define CDISASM_X86_DECODE_USE_3DNOW CDISASM_X86_DECODE_FLAG_3DNOW
#define CDISASM_X86_DECODE_USE_SSE CDISASM_X86_DECODE_FLAG_SSE
#define CDISASM_X86_DECODE_USE_SSE2 CDISASM_X86_DECODE_FLAG_SSE2
#define CDISASM_X86_DECODE_USE_SSE3 CDISASM_X86_DECODE_FLAG_SSE3
#define CDISASM_X86_DECODE_USE_SSSE3 CDISASM_X86_DECODE_FLAG_SSSE3
#define CDISASM_X86_DECODE_USE_SSE4 CDISASM_X86_DECODE_FLAG_SSE4
#define CDISASM_X86_DECODE_USE_AVX CDISASM_X86_DECODE_FLAG_AVX
#define CDISASM_X86_DECODE_USE_AVX2 CDISASM_X86_DECODE_FLAG_AVX2
#define CDISASM_X86_DECODE_USE_F16C CDISASM_X86_DECODE_FLAG_F16C
#define CDISASM_X86_DECODE_USE_FMA3 CDISASM_X86_DECODE_FLAG_FMA3
#define CDISASM_X86_DECODE_USE_XOP CDISASM_X86_DECODE_FLAG_XOP
#define CDISASM_X86_DECODE_USE_FMA4 CDISASM_X86_DECODE_FLAG_FMA4
#define CDISASM_X86_DECODE_USE_AES CDISASM_X86_DECODE_FLAG_AES
#define CDISASM_X86_DECODE_USE_PCLMUL CDISASM_X86_DECODE_FLAG_PCLMUL
#define CDISASM_X86_DECODE_USE_SHA CDISASM_X86_DECODE_FLAG_SHA
#define CDISASM_X86_DECODE_USE_GFNI CDISASM_X86_DECODE_FLAG_GFNI
#define CDISASM_X86_DECODE_USE_BITMANIP CDISASM_X86_DECODE_FLAG_BITMANIP
#define CDISASM_X86_DECODE_USE_AVX512 CDISASM_X86_DECODE_FLAG_AVX512
#define CDISASM_X86_DECODE_USE_AVX10 CDISASM_X86_DECODE_FLAG_AVX10
#define CDISASM_X86_DECODE_USE_AMX CDISASM_X86_DECODE_FLAG_AMX
#define CDISASM_X86_DECODE_USE_APX CDISASM_X86_DECODE_FLAG_APX
#define CDISASM_X86_DECODE_USE_SMX CDISASM_X86_DECODE_FLAG_SMX
#define CDISASM_X86_DECODE_USE_VIRTUALIZATION \
    CDISASM_X86_DECODE_FLAG_VIRTUALIZATION
#define CDISASM_X86_DECODE_USE_SYSTEM CDISASM_X86_DECODE_FLAG_SYSTEM
#define CDISASM_X86_DECODE_USE_CET CDISASM_X86_DECODE_FLAG_CET
#define CDISASM_X86_DECODE_USE_STATE CDISASM_X86_DECODE_FLAG_STATE
#define CDISASM_X86_DECODE_USE_TRANSACTIONAL \
    CDISASM_X86_DECODE_FLAG_TRANSACTIONAL
#define CDISASM_X86_DECODE_USE_SECURITY CDISASM_X86_DECODE_FLAG_SECURITY
#define CDISASM_X86_DECODE_USE_MEMORY_HINTS \
    CDISASM_X86_DECODE_FLAG_MEMORY_HINTS
#define CDISASM_X86_DECODE_USE_UNDOCUMENTED \
    CDISASM_X86_DECODE_FLAG_UNDOCUMENTED
#define CDISASM_X86_DECODE_USE_SM3 CDISASM_X86_DECODE_FLAG_SM3
#define CDISASM_X86_DECODE_USE_SM4 CDISASM_X86_DECODE_FLAG_SM4
#define CDISASM_X86_DECODE_USE_AVX512_VBMI2 \
    CDISASM_X86_DECODE_FLAG_AVX512_VBMI2
#define CDISASM_X86_DECODE_USE_AVX512_VPOPCNTDQ \
    CDISASM_X86_DECODE_FLAG_AVX512_VPOPCNTDQ
#define CDISASM_X86_DECODE_USE_AVX512_BITALG \
    CDISASM_X86_DECODE_FLAG_AVX512_BITALG
#define CDISASM_X86_DECODE_USE_COMPRESS_EXPAND \
    CDISASM_X86_DECODE_FLAG_COMPRESS_EXPAND
#define CDISASM_X86_DECODE_USE_AVX512_IFMA \
    CDISASM_X86_DECODE_FLAG_AVX512_IFMA
#define CDISASM_X86_DECODE_USE_AVX512_VBMI \
    CDISASM_X86_DECODE_FLAG_AVX512_VBMI
#define CDISASM_X86_DECODE_USE_AVX512_VNNI \
    CDISASM_X86_DECODE_FLAG_AVX512_VNNI
#define CDISASM_X86_DECODE_USE_VAES CDISASM_X86_DECODE_FLAG_VAES
#define CDISASM_X86_DECODE_USE_VPCLMULQDQ \
    CDISASM_X86_DECODE_FLAG_VPCLMULQDQ
#define CDISASM_X86_DECODE_USE_SHA512 CDISASM_X86_DECODE_FLAG_SHA512
#define CDISASM_X86_DECODE_USE_AMX_TILE CDISASM_X86_DECODE_FLAG_AMX_TILE
#define CDISASM_X86_DECODE_USE_AMX_INT8 CDISASM_X86_DECODE_FLAG_AMX_INT8
#define CDISASM_X86_DECODE_USE_AMX_BF16 CDISASM_X86_DECODE_FLAG_AMX_BF16
#define CDISASM_X86_DECODE_USE_AMX_FP16 CDISASM_X86_DECODE_FLAG_AMX_FP16
#define CDISASM_X86_DECODE_USE_AMX_COMPLEX \
    CDISASM_X86_DECODE_FLAG_AMX_COMPLEX
#define CDISASM_X86_DECODE_USE_AMX_FP8 CDISASM_X86_DECODE_FLAG_AMX_FP8
#define CDISASM_X86_DECODE_USE_AMX_MOVRS CDISASM_X86_DECODE_FLAG_AMX_MOVRS
#define CDISASM_X86_DECODE_USE_AMX_AVX512 \
    CDISASM_X86_DECODE_FLAG_AMX_AVX512
#define CDISASM_X86_DECODE_USE_AVX512_DQ \
    CDISASM_X86_DECODE_FLAG_AVX512_DQ
#define CDISASM_X86_DECODE_USE_AVX512_BW \
    CDISASM_X86_DECODE_FLAG_AVX512_BW
#define CDISASM_X86_DECODE_USE_VMX CDISASM_X86_DECODE_FLAG_VMX
#define CDISASM_X86_DECODE_USE_SVM CDISASM_X86_DECODE_FLAG_SVM
#define CDISASM_X86_DECODE_USE_INTEL_VIRTUALIZATION \
    CDISASM_X86_DECODE_FLAG_INTEL_VIRTUALIZATION
#define CDISASM_X86_DECODE_USE_AMD_VIRTUALIZATION \
    CDISASM_X86_DECODE_FLAG_AMD_VIRTUALIZATION
#define CDISASM_X86_DECODE_USE_SSE41 CDISASM_X86_DECODE_FLAG_SSE41
#define CDISASM_X86_DECODE_USE_SSE42 CDISASM_X86_DECODE_FLAG_SSE42
#define CDISASM_X86_DECODE_USE_SSE4A CDISASM_X86_DECODE_FLAG_SSE4A
#define CDISASM_X86_DECODE_USE_BMI1 CDISASM_X86_DECODE_FLAG_BMI1
#define CDISASM_X86_DECODE_USE_BMI2 CDISASM_X86_DECODE_FLAG_BMI2
#define CDISASM_X86_DECODE_USE_AVX512_CD \
    CDISASM_X86_DECODE_FLAG_AVX512_CD
#define CDISASM_X86_DECODE_USE_AVX_VNNI \
    CDISASM_X86_DECODE_FLAG_AVX_VNNI
#define CDISASM_X86_DECODE_USE_AVX_VNNI_INT8 \
    CDISASM_X86_DECODE_FLAG_AVX_VNNI_INT8
#define CDISASM_X86_DECODE_USE_AVX_VNNI_INT16 \
    CDISASM_X86_DECODE_FLAG_AVX_VNNI_INT16
#define CDISASM_X86_DECODE_USE_ALL CDISASM_X86_DECODE_FLAG_ALL
/* Source-compatibility aliases for the former decode2 API spelling. */
typedef cdisasm_x86_decode_option cdisasm_decode2_option;
#define CDISASM_DECODE2_OPTION_NONE CDISASM_X86_DECODE_OPTION_NONE

/** Prefix classes encountered in the decoded byte sequence. */
typedef uint32_t cdisasm_prefix;
#define CDISASM_PREFIX_NONE UINT32_C(0)
#define CDISASM_PREFIX_LOCK (UINT32_C(1) << 0)
#define CDISASM_PREFIX_REP (UINT32_C(1) << 1)
#define CDISASM_PREFIX_REPNE (UINT32_C(1) << 2)
#define CDISASM_PREFIX_OPERAND_SIZE (UINT32_C(1) << 3)
#define CDISASM_PREFIX_ADDRESS_SIZE (UINT32_C(1) << 4)
#define CDISASM_PREFIX_SEGMENT (UINT32_C(1) << 5)
#define CDISASM_PREFIX_REX (UINT32_C(1) << 6)
/** A VEX prefix is part of the effective instruction encoding. */
#define CDISASM_PREFIX_VEX (UINT32_C(1) << 7)
/** The rightmost effective REX prefix has its operand-width bit set. */
#define CDISASM_PREFIX_REX_W (UINT32_C(1) << 8)
/** WAIT/FWAIT is fused with a following x87 no-wait encoding. */
#define CDISASM_PREFIX_WAIT (UINT32_C(1) << 9)
/** AMD XOP prefix. */
#define CDISASM_PREFIX_XOP (UINT32_C(1) << 10)
/** Intel EVEX prefix (including the APX EVEX subspace). */
#define CDISASM_PREFIX_EVEX (UINT32_C(1) << 11)
/** Intel APX two-byte REX2 prefix. */
#define CDISASM_PREFIX_REX2 (UINT32_C(1) << 12)
/** APX new-data-destination semantics are active. */
#define CDISASM_PREFIX_APX_NDD (UINT32_C(1) << 13)
/** APX no-flags semantics are active. */
#define CDISASM_PREFIX_APX_NF (UINT32_C(1) << 14)
/** APX zero-upper semantics are active. */
#define CDISASM_PREFIX_APX_ZU (UINT32_C(1) << 15)
/** Ordinary effective prefix action, retained separately from encountered classes. */
#define CDISASM_PREFIX_EFFECTIVE_LOCK (UINT32_C(1) << 16)
#define CDISASM_PREFIX_EFFECTIVE_REP (UINT32_C(1) << 17)
#define CDISASM_PREFIX_EFFECTIVE_REPNE (UINT32_C(1) << 18)
#define CDISASM_PREFIX_EFFECTIVE_MASK \
    (CDISASM_PREFIX_EFFECTIVE_LOCK \
        | CDISASM_PREFIX_EFFECTIVE_REP \
        | CDISASM_PREFIX_EFFECTIVE_REPNE)
/** Effective HLE interpretation of the rightmost encountered F2/F3 prefix. */
#define CDISASM_PREFIX_XACQUIRE (UINT32_C(1) << 19)
#define CDISASM_PREFIX_XRELEASE (UINT32_C(1) << 20)
#define CDISASM_PREFIX_HLE_MASK \
    (CDISASM_PREFIX_XACQUIRE | CDISASM_PREFIX_XRELEASE)
#define CDISASM_PREFIX_HLE_XACQUIRE CDISASM_PREFIX_XACQUIRE
#define CDISASM_PREFIX_HLE_XRELEASE CDISASM_PREFIX_XRELEASE
/** Instruction reads one or more architectural status/control flags. */
#define CDISASM_X86_INSTRUCTION_FLAG_READS_STATUS_FLAGS \
    (UINT32_C(1) << 21)
/** Instruction writes, clears, sets, or undefines architectural flags. */
#define CDISASM_X86_INSTRUCTION_FLAG_WRITES_STATUS_FLAGS \
    (UINT32_C(1) << 22)
/** Result came from the generated, pinned-XED recognition fallback. */
#define CDISASM_X86_INSTRUCTION_FLAG_GENERATED_FALLBACK \
    (UINT32_C(1) << 30)
/** Encoding is exact, but structured operand recipes are not yet available. */
#define CDISASM_X86_INSTRUCTION_FLAG_OPERANDS_OPAQUE \
    (UINT32_C(1) << 31)

/**
 * One structured operand in Intel display order.
 *
 * size is measured in bytes, or is CDISASM_X86_OPERAND_SIZE_VARIABLE when an
 * architectural run-time configuration determines the size. For memory
 * operands, imm is the signed displacement bit pattern, scale is zero when
 * there is no index register,
 * and address is meaningful only with CDISASM_OPERAND_FLAG_HAS_ADDRESS. For
 * ordinary immediate operands imm is the semantic value. A PC-relative
 * immediate stores the resolved target in imm and its signed displacement in
 * address. reg, base_reg, index_reg, and segment_reg use the
 * CDISASM_X86_REG_* definitions. access records data flow and broadcast is a
 * literal 1-to-N element count. Unused fields and unused operand records are
 * zero.
 */
typedef struct cdisasm_opcode {
    uint8_t type;
    uint8_t size;
    uint8_t scale;
    uint8_t flags;
    cdisasm_x86_reg_id reg;
    cdisasm_x86_reg_id base_reg;
    cdisasm_x86_reg_id index_reg;
    cdisasm_x86_reg_id segment_reg;
    cdisasm_operand_access access;
    cdisasm_x86_broadcast broadcast;
    /** Reserved for ABI evolution; always zero. */
    uint8_t reserved[2];
    uint64_t address;
    uint64_t imm;
} cdisasm_opcode;
typedef cdisasm_opcode cdisasm_x86_operand;

/**
 * Byte offsets for the effective x86 encoding.
 *
 * Every offset is relative to the first instruction byte. An absent ModRM,
 * SIB, displacement, immediate, or opcode-selector byte has a zero size/count
 * and its corresponding offset/value fields are zero. selector_offset is the
 * trailing selector byte used by the 0F 0F 3DNow encoding and exact XOP
 * SE_IMM8 forms such as VPBLENDVB, VPCMOV, and VPPERM; that byte is encoding
 * metadata, not an immediate operand.
 */
typedef struct cdisasm_x86_encoding {
    uint8_t prefix_size;
    uint8_t opcode_offset;
    uint8_t opcode_size;
    uint8_t modrm_offset;
    uint8_t modrm;
    uint8_t sib_offset;
    uint8_t sib;
    uint8_t displacement_offset;
    uint8_t displacement_size;
    uint8_t immediate_count;
    uint8_t immediate_offset[2];
    uint8_t immediate_size[2];
    uint8_t selector_offset;
    /** Reserved for ABI evolution; always zero. */
    uint8_t reserved;
} cdisasm_x86_encoding;

/** Compact structured result produced by cdisasm_decode. */
typedef struct cdisasm_instruction {
    uint64_t address;
    uint64_t branch_target;
    uint32_t opcode_size;
    uint32_t opcode_groups;
    uint32_t opcode_flags;
    /** Effective x86 mnemonic, one of the CDISASM_X86_NAME_* definitions. */
    cdisasm_x86_name_id name_id;
    uint8_t last_error_id;
    uint8_t operand_count;
    cdisasm_opcode opcode[CDISASM_MAX_OPERANDS];
    /** Sorted, unique x86 ISA-family IDs describing the effective encoding. */
    uint8_t x86_group_count;
    /** Reserved for ABI evolution; always zero. */
    uint8_t x86_group_reserved;
    cdisasm_x86_group_id x86_group_ids[CDISASM_MAX_X86_GROUPS];
    /** EVEX/APX destination mask; NONE when the instruction is unmasked. */
    cdisasm_x86_reg_id mask_reg;
    cdisasm_x86_mask_mode mask_mode;
    cdisasm_x86_rounding_mode rounding;
    cdisasm_x86_sae sae;
    /** APX CCMP/CTEST default-flags value; zero when not encoded. */
    cdisasm_x86_default_flags default_flags;
    cdisasm_x86_form_id form_id;
    cdisasm_x86_encoding encoding;
} cdisasm_instruction;
typedef cdisasm_instruction cdisasm_x86_instruction;

#if defined(__cplusplus) && __cplusplus >= 201103L
static_assert(sizeof(cdisasm_opcode) == CDISASM_OPCODE_SIZE,
              "unexpected cdisasm_opcode ABI size");
static_assert(sizeof(cdisasm_x86_reg_id) == 2,
              "unexpected cdisasm x86 register-id size");
static_assert(offsetof(cdisasm_opcode, reg) == 4,
              "unexpected cdisasm_opcode ABI layout");
static_assert(offsetof(cdisasm_opcode, access) == 12,
              "unexpected cdisasm_opcode ABI layout");
static_assert(offsetof(cdisasm_opcode, address) == 16,
              "unexpected cdisasm_opcode ABI layout");
static_assert(offsetof(cdisasm_opcode, imm) == 24,
              "unexpected cdisasm_opcode ABI layout");
static_assert(sizeof(cdisasm_x86_encoding) == CDISASM_X86_ENCODING_SIZE,
              "unexpected cdisasm x86 encoding ABI size");
static_assert(sizeof(cdisasm_x86_name_id) == 2,
              "unexpected cdisasm x86 name-id size");
static_assert(sizeof(cdisasm_x86_group_id) == 2,
              "unexpected cdisasm x86 group-id size");
static_assert(sizeof(cdisasm_instruction) == CDISASM_INSTRUCTION_SIZE,
              "unexpected cdisasm_instruction ABI size");
static_assert(offsetof(cdisasm_instruction, name_id) == 28,
              "unexpected cdisasm_instruction name-id layout");
static_assert(offsetof(cdisasm_instruction, opcode) == 32,
              "unexpected cdisasm_instruction ABI layout");
static_assert(offsetof(cdisasm_instruction, x86_group_count) == 192,
              "unexpected cdisasm_instruction group-count layout");
static_assert(offsetof(cdisasm_instruction, x86_group_ids) == 194,
              "unexpected cdisasm_instruction group-id layout");
static_assert(offsetof(cdisasm_instruction, mask_reg) == 224,
              "unexpected cdisasm_instruction mask layout");
static_assert(offsetof(cdisasm_instruction, form_id) == 230,
              "unexpected cdisasm_instruction form-id layout");
static_assert(offsetof(cdisasm_instruction, encoding) == 232,
              "unexpected cdisasm_instruction encoding layout");
#elif defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
_Static_assert(sizeof(cdisasm_opcode) == CDISASM_OPCODE_SIZE,
               "unexpected cdisasm_opcode ABI size");
_Static_assert(sizeof(cdisasm_x86_reg_id) == 2,
               "unexpected cdisasm x86 register-id size");
_Static_assert(offsetof(cdisasm_opcode, reg) == 4,
               "unexpected cdisasm_opcode ABI layout");
_Static_assert(offsetof(cdisasm_opcode, access) == 12,
               "unexpected cdisasm_opcode ABI layout");
_Static_assert(offsetof(cdisasm_opcode, address) == 16,
               "unexpected cdisasm_opcode ABI layout");
_Static_assert(offsetof(cdisasm_opcode, imm) == 24,
               "unexpected cdisasm_opcode ABI layout");
_Static_assert(sizeof(cdisasm_x86_encoding) == CDISASM_X86_ENCODING_SIZE,
               "unexpected cdisasm x86 encoding ABI size");
_Static_assert(sizeof(cdisasm_x86_name_id) == 2,
               "unexpected cdisasm x86 name-id size");
_Static_assert(sizeof(cdisasm_x86_group_id) == 2,
               "unexpected cdisasm x86 group-id size");
_Static_assert(sizeof(cdisasm_instruction) == CDISASM_INSTRUCTION_SIZE,
               "unexpected cdisasm_instruction ABI size");
_Static_assert(offsetof(cdisasm_instruction, name_id) == 28,
               "unexpected cdisasm_instruction name-id layout");
_Static_assert(offsetof(cdisasm_instruction, opcode) == 32,
               "unexpected cdisasm_instruction ABI layout");
_Static_assert(offsetof(cdisasm_instruction, x86_group_count) == 192,
               "unexpected cdisasm_instruction group-count layout");
_Static_assert(offsetof(cdisasm_instruction, x86_group_ids) == 194,
               "unexpected cdisasm_instruction group-id layout");
_Static_assert(offsetof(cdisasm_instruction, mask_reg) == 224,
               "unexpected cdisasm_instruction mask layout");
_Static_assert(offsetof(cdisasm_instruction, form_id) == 230,
               "unexpected cdisasm_instruction form-id layout");
_Static_assert(offsetof(cdisasm_instruction, encoding) == 232,
               "unexpected cdisasm_instruction encoding layout");
#endif

/** Returns nonzero when instruction has the requested x86 ISA-family group. */
static inline int cdisasm_instruction_has_x86_group(
    const cdisasm_instruction *instruction,
    cdisasm_x86_group_id group_id)
{
    uint8_t index;

    if (instruction == NULL
        || instruction->x86_group_count > CDISASM_MAX_X86_GROUPS
        || group_id < CDISASM_X86_GROUP_FIRST
        || group_id > CDISASM_X86_GROUP_LAST) {
        return 0;
    }
    for (index = 0; index < instruction->x86_group_count; ++index) {
        if (instruction->x86_group_ids[index] == group_id) {
            return 1;
        }
        if (instruction->x86_group_ids[index] > group_id) {
            break;
        }
    }
    return 0;
}

/**
 * Returns the validation family selected by a decoded instruction.
 * CDISASM_X86_FAMILY_NONE means that the instruction is covered by the
 * ordinary ISA-group rules and does not need one of the special bundles.
 */
CDISASM_X86_API cdisasm_x86_family_id CDISASM_CALL
cdisasm_x86_instruction_family(const cdisasm_instruction *instruction);

/**
 * Returns immutable metadata for a direct or validation family, or NULL for
 * CDISASM_X86_FAMILY_NONE/an invalid family ID.
 */
CDISASM_X86_API const cdisasm_x86_family_descriptor *CDISASM_CALL
cdisasm_x86_family_descriptor_get(cdisasm_x86_family_id family_id);

/**
 * Converts an x86 decode-flag set to the direct and validation opcode
 * families it can select.  The result uses CDISASM_X86_FAMILY_MASK_* bits,
 * so multiple families can be returned at once.  NULL or an all-zero flag
 * set returns CDISASM_X86_FAMILY_MASK_NONE.  Exact ISA_SET bits are
 * considered in addition to the legacy bitmap-0 umbrella flags.  The
 * selected execution mode is reported separately by the context's mode
 * field and is not represented as an opcode family.
 */
CDISASM_X86_API cdisasm_x86_family_mask CDISASM_CALL
cdisasm_x86_family_mask_from_flags(
    const cdisasm_x86_decode_flags *flags);

/**
 * Returns the execution modes supported by the selected x86 CPU profile.
 *
 * Bits 0, 1, and 2 represent 16-, 32-, and 64-bit mode respectively.
 * Returns CDISASM_X86_MODE_MASK_NONE for an invalid or non-x86 CPU ID.
 */
CDISASM_X86_API cdisasm_x86_mode_mask CDISASM_CALL
cdisasm_x86_cpu_mode_mask(cdisasm_x86_cpu_id cpu_id);

/**
 * Writes the usable non-base decode-family flags for one CPU and mode.
 *
 * The output is cleared first. On success it contains only known x86 bits and
 * reflects both the exact CPU profile and opcode families implemented by this
 * build. Base scalar decoding is represented by an all-zero set and is always
 * implicit. The unrestricted CDISASM_CPU_X86 profile exposes every exact
 * family that has an encoding in the requested mode. Named profiles combine
 * their reviewed bitmap-0 feature masks with generated, mode-aware exact
 * ISA_SET masks derived from the pinned XED chip models; unsupported families
 * remain clear, including AVX families on the no-AVX low-end profiles. Invalid
 * arguments return CDISASM_STATUS_INVALID_ARGUMENT; a valid
 * USE_EXTRA_OPCODES=0 build returns OK with an all-zero set.
 */
CDISASM_X86_API cdisasm_status CDISASM_CALL
cdisasm_x86_cpu_decode_flag_mask(
    cdisasm_x86_cpu_id cpu_id,
    cdisasm_x86_mode mode,
    cdisasm_x86_decode_flags *flags);

/**
 * Initializes a CPU-bound decode context.  This is the convenient form for
 * callers that want to query the CPU once and then decode multiple raw
 * instructions without repeating CPU and mode arguments.
 */
CDISASM_X86_API cdisasm_status CDISASM_CALL
cdisasm_x86_cpu_decode_context(
    cdisasm_x86_cpu_id cpu_id,
    cdisasm_x86_mode mode,
    cdisasm_x86_decode_context *context);

/**
 * Decodes one instruction into compact structured metadata.
 *
 * Returns the decoded byte count (1..15), or zero on failure. When instruction
 * is non-NULL it is always initialized; last_error_id contains one of the
 * CDISASM_STATUS_* values and all other fields remain zero on failure. Named
 * CPU profiles restrict modes and instruction availability; CDISASM_CPU_X86
 * preserves unrestricted CPU capability behavior. The flags argument points
 * to an independent opcode-family bitmap set: NULL or all-zero selects only
 * base scalar
 * opcodes, and a non-base instruction's most-specific selectable family must
 * be enabled. Undocumented x87 forms require both FPU and UNDOCUMENTED.
 * Nonzero family flags are accepted only when USE_EXTRA_OPCODES is enabled.
 * Unknown bits in any bitmap are rejected with
 * CDISASM_STATUS_INVALID_ARGUMENT.
 */
CDISASM_X86_API uint32_t CDISASM_CALL cdisasm_x86_decode(
    cdisasm_cpu_id cpu_id,
    cdisasm_mode mode,
    const uint8_t *code,
    size_t code_size,
    uint64_t address,
    const cdisasm_x86_decode_flags *flags,
    cdisasm_instruction *instruction);

/** Decodes using a previously initialized CPU-bound context. */
CDISASM_X86_API uint32_t CDISASM_CALL cdisasm_x86_decode_with_context(
    const cdisasm_x86_decode_context *context,
    const uint8_t *code,
    size_t code_size,
    uint64_t address,
    cdisasm_instruction *instruction);

#ifdef __cplusplus
}
#endif

#endif
